"""Type stubs for the `splintr` package.

The API itself is described in `_core.pyi`, the compiled extension module this
re-exports from. `__init__.py` re-exports the same names at runtime.
"""

from typing import Final

from ._core import (
    Tokenizer as Tokenizer,
    SentencePieceTokenizer as SentencePieceTokenizer,
    SpmTokenizer as SpmTokenizer,
    WordPieceTokenizer as WordPieceTokenizer,
    AnyTokenizer as AnyTokenizer,
    from_json as from_json,
    from_json_bytes as from_json_bytes,
    base_vocab_size as base_vocab_size,
    StreamingDecoder as StreamingDecoder,
    CL100K_BASE_PATTERN as CL100K_BASE_PATTERN,
    KIMI_PATTERN as KIMI_PATTERN,
    QWEN2_PATTERN as QWEN2_PATTERN,
    O200K_BASE_PATTERN as O200K_BASE_PATTERN,
    LLAMA3_PATTERN as LLAMA3_PATTERN,
    MISTRAL_V3_PATTERN as MISTRAL_V3_PATTERN,
    GPT2_PATTERN as GPT2_PATTERN,
    CL100K_AGENT_TOKENS as CL100K_AGENT_TOKENS,
    O200K_AGENT_TOKENS as O200K_AGENT_TOKENS,
    LLAMA3_AGENT_TOKENS as LLAMA3_AGENT_TOKENS,
    DEEPSEEK_V3_AGENT_TOKENS as DEEPSEEK_V3_AGENT_TOKENS,
    QWEN3_AGENT_TOKENS as QWEN3_AGENT_TOKENS,
    GLM4_AGENT_TOKENS as GLM4_AGENT_TOKENS,
    GPT_OSS_AGENT_TOKENS as GPT_OSS_AGENT_TOKENS,
    KIMI_K2_AGENT_TOKENS as KIMI_K2_AGENT_TOKENS,
    KIMI_K3_AGENT_TOKENS as KIMI_K3_AGENT_TOKENS,
    MISTRAL_V1_AGENT_TOKENS as MISTRAL_V1_AGENT_TOKENS,
    MISTRAL_V2_AGENT_TOKENS as MISTRAL_V2_AGENT_TOKENS,
    MISTRAL_V3_AGENT_TOKENS as MISTRAL_V3_AGENT_TOKENS,
    PHI4_AGENT_TOKENS as PHI4_AGENT_TOKENS,
    OLMO2_AGENT_TOKENS as OLMO2_AGENT_TOKENS,
    LLAMA2_AGENT_TOKENS as LLAMA2_AGENT_TOKENS,
    CODELLAMA_AGENT_TOKENS as CODELLAMA_AGENT_TOKENS,
    MODERNBERT_AGENT_TOKENS as MODERNBERT_AGENT_TOKENS,
    GEMMA2_AGENT_TOKENS as GEMMA2_AGENT_TOKENS,
    GEMMA3_AGENT_TOKENS as GEMMA3_AGENT_TOKENS,
    GEMMA4_AGENT_TOKENS as GEMMA4_AGENT_TOKENS,
)

__version__: Final[str]

__all__ = [
    "Tokenizer",
    "SentencePieceTokenizer",
    "SpmTokenizer",
    "WordPieceTokenizer",
    "AnyTokenizer",
    "from_json",
    "from_json_bytes",
    "base_vocab_size",
    "StreamingDecoder",
    "CL100K_BASE_PATTERN",
    "KIMI_PATTERN",
    "QWEN2_PATTERN",
    "O200K_BASE_PATTERN",
    "LLAMA3_PATTERN",
    "MISTRAL_V3_PATTERN",
    "GPT2_PATTERN",
    "CL100K_AGENT_TOKENS",
    "O200K_AGENT_TOKENS",
    "LLAMA3_AGENT_TOKENS",
    "DEEPSEEK_V3_AGENT_TOKENS",
    "QWEN3_AGENT_TOKENS",
    "GLM4_AGENT_TOKENS",
    "GPT_OSS_AGENT_TOKENS",
    "KIMI_K2_AGENT_TOKENS",
    "KIMI_K3_AGENT_TOKENS",
    "MISTRAL_V1_AGENT_TOKENS",
    "MISTRAL_V2_AGENT_TOKENS",
    "MISTRAL_V3_AGENT_TOKENS",
    "PHI4_AGENT_TOKENS",
    "OLMO2_AGENT_TOKENS",
    "LLAMA2_AGENT_TOKENS",
    "CODELLAMA_AGENT_TOKENS",
    "MODERNBERT_AGENT_TOKENS",
    "GEMMA2_AGENT_TOKENS",
    "GEMMA3_AGENT_TOKENS",
    "GEMMA4_AGENT_TOKENS",
]
