// =============================================================================
// AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
// Generated by: scripts/generate_agent_tokens.py --lang rust
// Source of truth: AGENT_TOKENS and MODELS in that script
// =============================================================================
//
// Compile-time agent-token ids, one module per bundled vocabulary.
// Whisper has no module: it carries no agent tokens.
//
// Included by agent_tokens.rs, which holds the tests for these ids.

/// Agent tokens for cl100k_base (GPT-4, GPT-3.5-turbo).
///
/// The 54-token block starts at 100277. Every id here is also reachable
/// at runtime as `from_pretrained("cl100k_base")?.special_token_id(name)`;
/// these constants are the compile-time form, so a typo is a compile
/// error rather than a `None` to unwrap.
pub mod cl100k_agent_tokens {
    // Conversation & Roles
    /// System role - system instructions
    pub const SYSTEM: u32 = 100277;
    /// User role - user input
    pub const USER: u32 = 100278;
    /// Assistant role - model output
    pub const ASSISTANT: u32 = 100279;
    /// Start of message - ChatML wrapper
    pub const IM_START: u32 = 100280;
    /// End of message - ChatML wrapper
    pub const IM_END: u32 = 100281;

    // Reasoning/Thinking
    /// Start of thinking - Chain-of-Thought
    pub const THINK: u32 = 100282;
    /// End of thinking
    pub const THINK_END: u32 = 100283;

    // ReAct Agent Loop
    /// Start of plan - action planning
    pub const PLAN: u32 = 100284;
    /// End of plan
    pub const PLAN_END: u32 = 100285;
    /// Start of step - individual action step
    pub const STEP: u32 = 100286;
    /// End of step
    pub const STEP_END: u32 = 100287;
    /// Start of action - agent action
    pub const ACT: u32 = 100288;
    /// End of action
    pub const ACT_END: u32 = 100289;
    /// Start of observation - environment feedback
    pub const OBSERVE: u32 = 100290;
    /// End of observation
    pub const OBSERVE_END: u32 = 100291;

    // Tool/Function Calling
    /// Start of function call - function invocation
    pub const FUNCTION: u32 = 100292;
    /// End of function call
    pub const FUNCTION_END: u32 = 100293;
    /// Start of function result - return value
    pub const RESULT: u32 = 100294;
    /// End of function result
    pub const RESULT_END: u32 = 100295;
    /// Start of error - error message
    pub const ERROR: u32 = 100296;
    /// End of error
    pub const ERROR_END: u32 = 100297;

    // Code Execution
    /// Start of code - inline code execution
    pub const CODE: u32 = 100298;
    /// End of code
    pub const CODE_END: u32 = 100299;
    /// Start of output - execution output
    pub const OUTPUT: u32 = 100300;
    /// End of output
    pub const OUTPUT_END: u32 = 100301;
    /// Start of language tag - code language
    pub const LANG: u32 = 100302;
    /// End of language tag
    pub const LANG_END: u32 = 100303;

    // RAG & Citations
    /// Start of context - retrieved context
    pub const CONTEXT: u32 = 100304;
    /// End of context
    pub const CONTEXT_END: u32 = 100305;
    /// Start of quote - exact citation
    pub const QUOTE: u32 = 100306;
    /// End of quote
    pub const QUOTE_END: u32 = 100307;
    /// Start of cite - citation reference
    pub const CITE: u32 = 100308;
    /// End of cite
    pub const CITE_END: u32 = 100309;
    /// Start of source - document source
    pub const SOURCE: u32 = 100310;
    /// End of source
    pub const SOURCE_END: u32 = 100311;

    // Memory/State Management
    /// Start of memory - persistent memory
    pub const MEMORY: u32 = 100312;
    /// End of memory
    pub const MEMORY_END: u32 = 100313;
    /// Start of recall - memory retrieval
    pub const RECALL: u32 = 100314;
    /// End of recall
    pub const RECALL_END: u32 = 100315;

    // Control Tokens
    /// Padding token
    pub const PAD: u32 = 100316;
    /// Stop generation token
    pub const STOP: u32 = 100317;
    /// Separator token
    pub const SEP: u32 = 100318;

    // Multimodal Placeholders
    /// Start of image - image placeholder
    pub const IMAGE: u32 = 100319;
    /// End of image
    pub const IMAGE_END: u32 = 100320;
    /// Start of audio - audio placeholder
    pub const AUDIO: u32 = 100321;
    /// End of audio
    pub const AUDIO_END: u32 = 100322;
    /// Start of video - video placeholder
    pub const VIDEO: u32 = 100323;
    /// End of video
    pub const VIDEO_END: u32 = 100324;

    // Document Structure
    /// Start of title - document/section title
    pub const TITLE: u32 = 100325;
    /// End of title
    pub const TITLE_END: u32 = 100326;
    /// Start of section - semantic document section
    pub const SECTION: u32 = 100327;
    /// End of section
    pub const SECTION_END: u32 = 100328;
    /// Start of summary - condensed content summary
    pub const SUMMARY: u32 = 100329;
    /// End of summary
    pub const SUMMARY_END: u32 = 100330;
}

/// Agent tokens for o200k_base (GPT-4o).
///
/// The 54-token block starts at 200019. Every id here is also reachable
/// at runtime as `from_pretrained("o200k_base")?.special_token_id(name)`;
/// these constants are the compile-time form, so a typo is a compile
/// error rather than a `None` to unwrap.
pub mod o200k_agent_tokens {
    // Conversation & Roles
    /// System role - system instructions
    pub const SYSTEM: u32 = 200019;
    /// User role - user input
    pub const USER: u32 = 200020;
    /// Assistant role - model output
    pub const ASSISTANT: u32 = 200021;
    /// Start of message - ChatML wrapper
    pub const IM_START: u32 = 200022;
    /// End of message - ChatML wrapper
    pub const IM_END: u32 = 200023;

    // Reasoning/Thinking
    /// Start of thinking - Chain-of-Thought
    pub const THINK: u32 = 200024;
    /// End of thinking
    pub const THINK_END: u32 = 200025;

    // ReAct Agent Loop
    /// Start of plan - action planning
    pub const PLAN: u32 = 200026;
    /// End of plan
    pub const PLAN_END: u32 = 200027;
    /// Start of step - individual action step
    pub const STEP: u32 = 200028;
    /// End of step
    pub const STEP_END: u32 = 200029;
    /// Start of action - agent action
    pub const ACT: u32 = 200030;
    /// End of action
    pub const ACT_END: u32 = 200031;
    /// Start of observation - environment feedback
    pub const OBSERVE: u32 = 200032;
    /// End of observation
    pub const OBSERVE_END: u32 = 200033;

    // Tool/Function Calling
    /// Start of function call - function invocation
    pub const FUNCTION: u32 = 200034;
    /// End of function call
    pub const FUNCTION_END: u32 = 200035;
    /// Start of function result - return value
    pub const RESULT: u32 = 200036;
    /// End of function result
    pub const RESULT_END: u32 = 200037;
    /// Start of error - error message
    pub const ERROR: u32 = 200038;
    /// End of error
    pub const ERROR_END: u32 = 200039;

    // Code Execution
    /// Start of code - inline code execution
    pub const CODE: u32 = 200040;
    /// End of code
    pub const CODE_END: u32 = 200041;
    /// Start of output - execution output
    pub const OUTPUT: u32 = 200042;
    /// End of output
    pub const OUTPUT_END: u32 = 200043;
    /// Start of language tag - code language
    pub const LANG: u32 = 200044;
    /// End of language tag
    pub const LANG_END: u32 = 200045;

    // RAG & Citations
    /// Start of context - retrieved context
    pub const CONTEXT: u32 = 200046;
    /// End of context
    pub const CONTEXT_END: u32 = 200047;
    /// Start of quote - exact citation
    pub const QUOTE: u32 = 200048;
    /// End of quote
    pub const QUOTE_END: u32 = 200049;
    /// Start of cite - citation reference
    pub const CITE: u32 = 200050;
    /// End of cite
    pub const CITE_END: u32 = 200051;
    /// Start of source - document source
    pub const SOURCE: u32 = 200052;
    /// End of source
    pub const SOURCE_END: u32 = 200053;

    // Memory/State Management
    /// Start of memory - persistent memory
    pub const MEMORY: u32 = 200054;
    /// End of memory
    pub const MEMORY_END: u32 = 200055;
    /// Start of recall - memory retrieval
    pub const RECALL: u32 = 200056;
    /// End of recall
    pub const RECALL_END: u32 = 200057;

    // Control Tokens
    /// Padding token
    pub const PAD: u32 = 200058;
    /// Stop generation token
    pub const STOP: u32 = 200059;
    /// Separator token
    pub const SEP: u32 = 200060;

    // Multimodal Placeholders
    /// Start of image - image placeholder
    pub const IMAGE: u32 = 200061;
    /// End of image
    pub const IMAGE_END: u32 = 200062;
    /// Start of audio - audio placeholder
    pub const AUDIO: u32 = 200063;
    /// End of audio
    pub const AUDIO_END: u32 = 200064;
    /// Start of video - video placeholder
    pub const VIDEO: u32 = 200065;
    /// End of video
    pub const VIDEO_END: u32 = 200066;

    // Document Structure
    /// Start of title - document/section title
    pub const TITLE: u32 = 200067;
    /// End of title
    pub const TITLE_END: u32 = 200068;
    /// Start of section - semantic document section
    pub const SECTION: u32 = 200069;
    /// End of section
    pub const SECTION_END: u32 = 200070;
    /// Start of summary - condensed content summary
    pub const SUMMARY: u32 = 200071;
    /// End of summary
    pub const SUMMARY_END: u32 = 200072;
}

/// Agent tokens for Llama 3 family.
///
/// The 54-token block starts at 128300. Every id here is also reachable
/// at runtime as `from_pretrained("llama3")?.special_token_id(name)`;
/// these constants are the compile-time form, so a typo is a compile
/// error rather than a `None` to unwrap.
///
/// Llama 3 family defines AUDIO, AUDIO_END, IMAGE, IMAGE_END, VIDEO, VIDEO_END itself, so those constants carry the
/// vocabulary's own id — below `base_vocab_size`, the id the checkpoint
/// was trained on — rather than a splintr-appended one.
///
/// The vocabulary's own markers are included too, so this module is its
/// whole special-token surface. A native name that would collide with
/// an agent token of the same meaning takes a `_NATIVE` suffix.
pub mod llama3_agent_tokens {
    // Vocabulary-native tokens
    /// Start of text marker
    pub const BEGIN_OF_TEXT: u32 = 128000;
    /// End of text marker
    pub const END_OF_TEXT: u32 = 128001;
    /// Padding token for fine-tuning - added in Llama 3.1
    pub const FINETUNE_RIGHT_PAD_ID: u32 = 128004;
    /// Step marker for reasoning - added in Llama 3.2-Vision
    pub const STEP_ID: u32 = 128005;
    /// Start of header marker
    pub const START_HEADER_ID: u32 = 128006;
    /// End of header marker
    pub const END_HEADER_ID: u32 = 128007;
    /// End of message marker for tool use - added in Llama 3.1
    pub const EOM_ID: u32 = 128008;
    /// End of turn marker
    pub const EOT_ID: u32 = 128009;
    /// Python code interpreter marker - added in Llama 3.1
    pub const PYTHON_TAG: u32 = 128010;
    /// Image placeholder - Llama 3.2-Vision official
    pub const IMAGE: u32 = 128256;
    /// End of image placeholder
    pub const IMAGE_END: u32 = 128257;
    /// Audio placeholder
    pub const AUDIO: u32 = 128258;
    /// End of audio placeholder
    pub const AUDIO_END: u32 = 128259;
    /// Video placeholder
    pub const VIDEO: u32 = 128260;
    /// End of video placeholder
    pub const VIDEO_END: u32 = 128261;

    // Conversation & Roles
    /// System role - system instructions
    pub const SYSTEM: u32 = 128300;
    /// User role - user input
    pub const USER: u32 = 128301;
    /// Assistant role - model output
    pub const ASSISTANT: u32 = 128302;
    /// Start of message - ChatML wrapper
    pub const IM_START: u32 = 128303;
    /// End of message - ChatML wrapper
    pub const IM_END: u32 = 128304;

    // Reasoning/Thinking
    /// Start of thinking - Chain-of-Thought
    pub const THINK: u32 = 128305;
    /// End of thinking
    pub const THINK_END: u32 = 128306;

    // ReAct Agent Loop
    /// Start of plan - action planning
    pub const PLAN: u32 = 128307;
    /// End of plan
    pub const PLAN_END: u32 = 128308;
    /// Start of step - individual action step
    pub const STEP: u32 = 128309;
    /// End of step
    pub const STEP_END: u32 = 128310;
    /// Start of action - agent action
    pub const ACT: u32 = 128311;
    /// End of action
    pub const ACT_END: u32 = 128312;
    /// Start of observation - environment feedback
    pub const OBSERVE: u32 = 128313;
    /// End of observation
    pub const OBSERVE_END: u32 = 128314;

    // Tool/Function Calling
    /// Start of function call - function invocation
    pub const FUNCTION: u32 = 128315;
    /// End of function call
    pub const FUNCTION_END: u32 = 128316;
    /// Start of function result - return value
    pub const RESULT: u32 = 128317;
    /// End of function result
    pub const RESULT_END: u32 = 128318;
    /// Start of error - error message
    pub const ERROR: u32 = 128319;
    /// End of error
    pub const ERROR_END: u32 = 128320;

    // Code Execution
    /// Start of code - inline code execution
    pub const CODE: u32 = 128321;
    /// End of code
    pub const CODE_END: u32 = 128322;
    /// Start of output - execution output
    pub const OUTPUT: u32 = 128323;
    /// End of output
    pub const OUTPUT_END: u32 = 128324;
    /// Start of language tag - code language
    pub const LANG: u32 = 128325;
    /// End of language tag
    pub const LANG_END: u32 = 128326;

    // RAG & Citations
    /// Start of context - retrieved context
    pub const CONTEXT: u32 = 128327;
    /// End of context
    pub const CONTEXT_END: u32 = 128328;
    /// Start of quote - exact citation
    pub const QUOTE: u32 = 128329;
    /// End of quote
    pub const QUOTE_END: u32 = 128330;
    /// Start of cite - citation reference
    pub const CITE: u32 = 128331;
    /// End of cite
    pub const CITE_END: u32 = 128332;
    /// Start of source - document source
    pub const SOURCE: u32 = 128333;
    /// End of source
    pub const SOURCE_END: u32 = 128334;

    // Memory/State Management
    /// Start of memory - persistent memory
    pub const MEMORY: u32 = 128335;
    /// End of memory
    pub const MEMORY_END: u32 = 128336;
    /// Start of recall - memory retrieval
    pub const RECALL: u32 = 128337;
    /// End of recall
    pub const RECALL_END: u32 = 128338;

    // Control Tokens
    /// Padding token
    pub const PAD: u32 = 128339;
    /// Stop generation token
    pub const STOP: u32 = 128340;
    /// Separator token
    pub const SEP: u32 = 128341;

    // Document Structure
    /// Start of title - document/section title
    pub const TITLE: u32 = 128348;
    /// End of title
    pub const TITLE_END: u32 = 128349;
    /// Start of section - semantic document section
    pub const SECTION: u32 = 128350;
    /// End of section
    pub const SECTION_END: u32 = 128351;
    /// Start of summary - condensed content summary
    pub const SUMMARY: u32 = 128352;
    /// End of summary
    pub const SUMMARY_END: u32 = 128353;
}

/// Agent tokens for DeepSeek V3/R1.
///
/// The 54-token block starts at 128900. Every id here is also reachable
/// at runtime as `from_pretrained("deepseek_v3")?.special_token_id(name)`;
/// these constants are the compile-time form, so a typo is a compile
/// error rather than a `None` to unwrap.
///
/// The vocabulary's own markers are included too, so this module is its
/// whole special-token surface. A native name that would collide with
/// an agent token of the same meaning takes a `_NATIVE` suffix.
pub mod deepseek_v3_agent_tokens {
    // Vocabulary-native tokens
    /// Begin of sentence marker
    pub const BEGIN_OF_SENTENCE: u32 = 0;
    /// End of sentence marker
    pub const END_OF_SENTENCE: u32 = 1;
    /// Native padding token
    pub const PAD_NATIVE: u32 = 2;
    /// Native `<think>` token
    pub const THINK_NATIVE: u32 = 128798;
    /// Native `</think>` token
    pub const THINK_END_NATIVE: u32 = 128799;
    /// Fill-in-the-Middle hole
    pub const FIM_HOLE: u32 = 128800;
    /// Fill-in-the-Middle begin
    pub const FIM_BEGIN: u32 = 128801;
    /// Fill-in-the-Middle end
    pub const FIM_END: u32 = 128802;
    /// Native `<｜User｜>` token
    pub const USER_NATIVE: u32 = 128803;
    /// Native `<｜Assistant｜>` token
    pub const ASSISTANT_NATIVE: u32 = 128804;
    /// End of turn `<|EOT|>`
    pub const EOT: u32 = 128805;
    /// Tool calls begin marker
    pub const TOOL_CALLS_BEGIN: u32 = 128806;
    /// Tool calls end marker
    pub const TOOL_CALLS_END: u32 = 128807;
    /// Single tool call begin
    pub const TOOL_CALL_BEGIN: u32 = 128808;
    /// Single tool call end
    pub const TOOL_CALL_END: u32 = 128809;
    /// Tool outputs begin marker
    pub const TOOL_OUTPUTS_BEGIN: u32 = 128810;
    /// Tool outputs end marker
    pub const TOOL_OUTPUTS_END: u32 = 128811;
    /// Single tool output begin
    pub const TOOL_OUTPUT_BEGIN: u32 = 128812;
    /// Single tool output end
    pub const TOOL_OUTPUT_END: u32 = 128813;
    /// Tool separator
    pub const TOOL_SEP: u32 = 128814;

    // Conversation & Roles
    /// System role - system instructions
    pub const SYSTEM: u32 = 128900;
    /// User role - user input
    pub const USER: u32 = 128901;
    /// Assistant role - model output
    pub const ASSISTANT: u32 = 128902;
    /// Start of message - ChatML wrapper
    pub const IM_START: u32 = 128903;
    /// End of message - ChatML wrapper
    pub const IM_END: u32 = 128904;

    // Reasoning/Thinking
    /// Start of thinking - Chain-of-Thought
    pub const THINK: u32 = 128905;
    /// End of thinking
    pub const THINK_END: u32 = 128906;

    // ReAct Agent Loop
    /// Start of plan - action planning
    pub const PLAN: u32 = 128907;
    /// End of plan
    pub const PLAN_END: u32 = 128908;
    /// Start of step - individual action step
    pub const STEP: u32 = 128909;
    /// End of step
    pub const STEP_END: u32 = 128910;
    /// Start of action - agent action
    pub const ACT: u32 = 128911;
    /// End of action
    pub const ACT_END: u32 = 128912;
    /// Start of observation - environment feedback
    pub const OBSERVE: u32 = 128913;
    /// End of observation
    pub const OBSERVE_END: u32 = 128914;

    // Tool/Function Calling
    /// Start of function call - function invocation
    pub const FUNCTION: u32 = 128915;
    /// End of function call
    pub const FUNCTION_END: u32 = 128916;
    /// Start of function result - return value
    pub const RESULT: u32 = 128917;
    /// End of function result
    pub const RESULT_END: u32 = 128918;
    /// Start of error - error message
    pub const ERROR: u32 = 128919;
    /// End of error
    pub const ERROR_END: u32 = 128920;

    // Code Execution
    /// Start of code - inline code execution
    pub const CODE: u32 = 128921;
    /// End of code
    pub const CODE_END: u32 = 128922;
    /// Start of output - execution output
    pub const OUTPUT: u32 = 128923;
    /// End of output
    pub const OUTPUT_END: u32 = 128924;
    /// Start of language tag - code language
    pub const LANG: u32 = 128925;
    /// End of language tag
    pub const LANG_END: u32 = 128926;

    // RAG & Citations
    /// Start of context - retrieved context
    pub const CONTEXT: u32 = 128927;
    /// End of context
    pub const CONTEXT_END: u32 = 128928;
    /// Start of quote - exact citation
    pub const QUOTE: u32 = 128929;
    /// End of quote
    pub const QUOTE_END: u32 = 128930;
    /// Start of cite - citation reference
    pub const CITE: u32 = 128931;
    /// End of cite
    pub const CITE_END: u32 = 128932;
    /// Start of source - document source
    pub const SOURCE: u32 = 128933;
    /// End of source
    pub const SOURCE_END: u32 = 128934;

    // Memory/State Management
    /// Start of memory - persistent memory
    pub const MEMORY: u32 = 128935;
    /// End of memory
    pub const MEMORY_END: u32 = 128936;
    /// Start of recall - memory retrieval
    pub const RECALL: u32 = 128937;
    /// End of recall
    pub const RECALL_END: u32 = 128938;

    // Control Tokens
    /// Padding token
    pub const PAD: u32 = 128939;
    /// Stop generation token
    pub const STOP: u32 = 128940;
    /// Separator token
    pub const SEP: u32 = 128941;

    // Multimodal Placeholders
    /// Start of image - image placeholder
    pub const IMAGE: u32 = 128942;
    /// End of image
    pub const IMAGE_END: u32 = 128943;
    /// Start of audio - audio placeholder
    pub const AUDIO: u32 = 128944;
    /// End of audio
    pub const AUDIO_END: u32 = 128945;
    /// Start of video - video placeholder
    pub const VIDEO: u32 = 128946;
    /// End of video
    pub const VIDEO_END: u32 = 128947;

    // Document Structure
    /// Start of title - document/section title
    pub const TITLE: u32 = 128948;
    /// End of title
    pub const TITLE_END: u32 = 128949;
    /// Start of section - semantic document section
    pub const SECTION: u32 = 128950;
    /// End of section
    pub const SECTION_END: u32 = 128951;
    /// Start of summary - condensed content summary
    pub const SUMMARY: u32 = 128952;
    /// End of summary
    pub const SUMMARY_END: u32 = 128953;
}

/// Agent tokens for Mistral V1 (7B v0.1/v0.2, Mixtral 8x7B).
///
/// The 54-token block starts at 32000. Every id here is also reachable
/// at runtime as `from_pretrained("mistral_v1")?.special_token_id(name)`;
/// these constants are the compile-time form, so a typo is a compile
/// error rather than a `None` to unwrap.
pub mod mistral_v1_agent_tokens {
    // Conversation & Roles
    /// System role - system instructions
    pub const SYSTEM: u32 = 32000;
    /// User role - user input
    pub const USER: u32 = 32001;
    /// Assistant role - model output
    pub const ASSISTANT: u32 = 32002;
    /// Start of message - ChatML wrapper
    pub const IM_START: u32 = 32003;
    /// End of message - ChatML wrapper
    pub const IM_END: u32 = 32004;

    // Reasoning/Thinking
    /// Start of thinking - Chain-of-Thought
    pub const THINK: u32 = 32005;
    /// End of thinking
    pub const THINK_END: u32 = 32006;

    // ReAct Agent Loop
    /// Start of plan - action planning
    pub const PLAN: u32 = 32007;
    /// End of plan
    pub const PLAN_END: u32 = 32008;
    /// Start of step - individual action step
    pub const STEP: u32 = 32009;
    /// End of step
    pub const STEP_END: u32 = 32010;
    /// Start of action - agent action
    pub const ACT: u32 = 32011;
    /// End of action
    pub const ACT_END: u32 = 32012;
    /// Start of observation - environment feedback
    pub const OBSERVE: u32 = 32013;
    /// End of observation
    pub const OBSERVE_END: u32 = 32014;

    // Tool/Function Calling
    /// Start of function call - function invocation
    pub const FUNCTION: u32 = 32015;
    /// End of function call
    pub const FUNCTION_END: u32 = 32016;
    /// Start of function result - return value
    pub const RESULT: u32 = 32017;
    /// End of function result
    pub const RESULT_END: u32 = 32018;
    /// Start of error - error message
    pub const ERROR: u32 = 32019;
    /// End of error
    pub const ERROR_END: u32 = 32020;

    // Code Execution
    /// Start of code - inline code execution
    pub const CODE: u32 = 32021;
    /// End of code
    pub const CODE_END: u32 = 32022;
    /// Start of output - execution output
    pub const OUTPUT: u32 = 32023;
    /// End of output
    pub const OUTPUT_END: u32 = 32024;
    /// Start of language tag - code language
    pub const LANG: u32 = 32025;
    /// End of language tag
    pub const LANG_END: u32 = 32026;

    // RAG & Citations
    /// Start of context - retrieved context
    pub const CONTEXT: u32 = 32027;
    /// End of context
    pub const CONTEXT_END: u32 = 32028;
    /// Start of quote - exact citation
    pub const QUOTE: u32 = 32029;
    /// End of quote
    pub const QUOTE_END: u32 = 32030;
    /// Start of cite - citation reference
    pub const CITE: u32 = 32031;
    /// End of cite
    pub const CITE_END: u32 = 32032;
    /// Start of source - document source
    pub const SOURCE: u32 = 32033;
    /// End of source
    pub const SOURCE_END: u32 = 32034;

    // Memory/State Management
    /// Start of memory - persistent memory
    pub const MEMORY: u32 = 32035;
    /// End of memory
    pub const MEMORY_END: u32 = 32036;
    /// Start of recall - memory retrieval
    pub const RECALL: u32 = 32037;
    /// End of recall
    pub const RECALL_END: u32 = 32038;

    // Control Tokens
    /// Padding token
    pub const PAD: u32 = 32039;
    /// Stop generation token
    pub const STOP: u32 = 32040;
    /// Separator token
    pub const SEP: u32 = 32041;

    // Multimodal Placeholders
    /// Start of image - image placeholder
    pub const IMAGE: u32 = 32042;
    /// End of image
    pub const IMAGE_END: u32 = 32043;
    /// Start of audio - audio placeholder
    pub const AUDIO: u32 = 32044;
    /// End of audio
    pub const AUDIO_END: u32 = 32045;
    /// Start of video - video placeholder
    pub const VIDEO: u32 = 32046;
    /// End of video
    pub const VIDEO_END: u32 = 32047;

    // Document Structure
    /// Start of title - document/section title
    pub const TITLE: u32 = 32048;
    /// End of title
    pub const TITLE_END: u32 = 32049;
    /// Start of section - semantic document section
    pub const SECTION: u32 = 32050;
    /// End of section
    pub const SECTION_END: u32 = 32051;
    /// Start of summary - condensed content summary
    pub const SUMMARY: u32 = 32052;
    /// End of summary
    pub const SUMMARY_END: u32 = 32053;
}

/// Agent tokens for Mistral V2 (7B v0.3, Mixtral 8x22B, Codestral).
///
/// The 54-token block starts at 32768. Every id here is also reachable
/// at runtime as `from_pretrained("mistral_v2")?.special_token_id(name)`;
/// these constants are the compile-time form, so a typo is a compile
/// error rather than a `None` to unwrap.
pub mod mistral_v2_agent_tokens {
    // Conversation & Roles
    /// System role - system instructions
    pub const SYSTEM: u32 = 32768;
    /// User role - user input
    pub const USER: u32 = 32769;
    /// Assistant role - model output
    pub const ASSISTANT: u32 = 32770;
    /// Start of message - ChatML wrapper
    pub const IM_START: u32 = 32771;
    /// End of message - ChatML wrapper
    pub const IM_END: u32 = 32772;

    // Reasoning/Thinking
    /// Start of thinking - Chain-of-Thought
    pub const THINK: u32 = 32773;
    /// End of thinking
    pub const THINK_END: u32 = 32774;

    // ReAct Agent Loop
    /// Start of plan - action planning
    pub const PLAN: u32 = 32775;
    /// End of plan
    pub const PLAN_END: u32 = 32776;
    /// Start of step - individual action step
    pub const STEP: u32 = 32777;
    /// End of step
    pub const STEP_END: u32 = 32778;
    /// Start of action - agent action
    pub const ACT: u32 = 32779;
    /// End of action
    pub const ACT_END: u32 = 32780;
    /// Start of observation - environment feedback
    pub const OBSERVE: u32 = 32781;
    /// End of observation
    pub const OBSERVE_END: u32 = 32782;

    // Tool/Function Calling
    /// Start of function call - function invocation
    pub const FUNCTION: u32 = 32783;
    /// End of function call
    pub const FUNCTION_END: u32 = 32784;
    /// Start of function result - return value
    pub const RESULT: u32 = 32785;
    /// End of function result
    pub const RESULT_END: u32 = 32786;
    /// Start of error - error message
    pub const ERROR: u32 = 32787;
    /// End of error
    pub const ERROR_END: u32 = 32788;

    // Code Execution
    /// Start of code - inline code execution
    pub const CODE: u32 = 32789;
    /// End of code
    pub const CODE_END: u32 = 32790;
    /// Start of output - execution output
    pub const OUTPUT: u32 = 32791;
    /// End of output
    pub const OUTPUT_END: u32 = 32792;
    /// Start of language tag - code language
    pub const LANG: u32 = 32793;
    /// End of language tag
    pub const LANG_END: u32 = 32794;

    // RAG & Citations
    /// Start of context - retrieved context
    pub const CONTEXT: u32 = 32795;
    /// End of context
    pub const CONTEXT_END: u32 = 32796;
    /// Start of quote - exact citation
    pub const QUOTE: u32 = 32797;
    /// End of quote
    pub const QUOTE_END: u32 = 32798;
    /// Start of cite - citation reference
    pub const CITE: u32 = 32799;
    /// End of cite
    pub const CITE_END: u32 = 32800;
    /// Start of source - document source
    pub const SOURCE: u32 = 32801;
    /// End of source
    pub const SOURCE_END: u32 = 32802;

    // Memory/State Management
    /// Start of memory - persistent memory
    pub const MEMORY: u32 = 32803;
    /// End of memory
    pub const MEMORY_END: u32 = 32804;
    /// Start of recall - memory retrieval
    pub const RECALL: u32 = 32805;
    /// End of recall
    pub const RECALL_END: u32 = 32806;

    // Control Tokens
    /// Padding token
    pub const PAD: u32 = 32807;
    /// Stop generation token
    pub const STOP: u32 = 32808;
    /// Separator token
    pub const SEP: u32 = 32809;

    // Multimodal Placeholders
    /// Start of image - image placeholder
    pub const IMAGE: u32 = 32810;
    /// End of image
    pub const IMAGE_END: u32 = 32811;
    /// Start of audio - audio placeholder
    pub const AUDIO: u32 = 32812;
    /// End of audio
    pub const AUDIO_END: u32 = 32813;
    /// Start of video - video placeholder
    pub const VIDEO: u32 = 32814;
    /// End of video
    pub const VIDEO_END: u32 = 32815;

    // Document Structure
    /// Start of title - document/section title
    pub const TITLE: u32 = 32816;
    /// End of title
    pub const TITLE_END: u32 = 32817;
    /// Start of section - semantic document section
    pub const SECTION: u32 = 32818;
    /// End of section
    pub const SECTION_END: u32 = 32819;
    /// Start of summary - condensed content summary
    pub const SUMMARY: u32 = 32820;
    /// End of summary
    pub const SUMMARY_END: u32 = 32821;
}

/// Agent tokens for Mistral V3/Tekken (NeMo, Large 2, Pixtral).
///
/// The 54-token block starts at 131072. Every id here is also reachable
/// at runtime as `from_pretrained("mistral_v3")?.special_token_id(name)`;
/// these constants are the compile-time form, so a typo is a compile
/// error rather than a `None` to unwrap.
///
/// The vocabulary's own markers are included too, so this module is its
/// whole special-token surface. A native name that would collide with
/// an agent token of the same meaning takes a `_NATIVE` suffix.
pub mod mistral_v3_agent_tokens {
    // Vocabulary-native tokens
    /// `[INST]` instruction begin
    pub const INST: u32 = 3;
    /// `[/INST]` instruction end
    pub const INST_END: u32 = 4;
    /// `[AVAILABLE_TOOLS]` tool list begin
    pub const AVAILABLE_TOOLS: u32 = 5;
    /// `[/AVAILABLE_TOOLS]` tool list end
    pub const AVAILABLE_TOOLS_END: u32 = 6;
    /// `[TOOL_RESULTS]` tool results begin
    pub const TOOL_RESULTS: u32 = 7;
    /// `[/TOOL_RESULTS]` tool results end
    pub const TOOL_RESULTS_END: u32 = 8;
    /// `[TOOL_CALLS]` tool calls marker
    pub const TOOL_CALLS: u32 = 9;

    // Conversation & Roles
    /// System role - system instructions
    pub const SYSTEM: u32 = 131072;
    /// User role - user input
    pub const USER: u32 = 131073;
    /// Assistant role - model output
    pub const ASSISTANT: u32 = 131074;
    /// Start of message - ChatML wrapper
    pub const IM_START: u32 = 131075;
    /// End of message - ChatML wrapper
    pub const IM_END: u32 = 131076;

    // Reasoning/Thinking
    /// Start of thinking - Chain-of-Thought
    pub const THINK: u32 = 131077;
    /// End of thinking
    pub const THINK_END: u32 = 131078;

    // ReAct Agent Loop
    /// Start of plan - action planning
    pub const PLAN: u32 = 131079;
    /// End of plan
    pub const PLAN_END: u32 = 131080;
    /// Start of step - individual action step
    pub const STEP: u32 = 131081;
    /// End of step
    pub const STEP_END: u32 = 131082;
    /// Start of action - agent action
    pub const ACT: u32 = 131083;
    /// End of action
    pub const ACT_END: u32 = 131084;
    /// Start of observation - environment feedback
    pub const OBSERVE: u32 = 131085;
    /// End of observation
    pub const OBSERVE_END: u32 = 131086;

    // Tool/Function Calling
    /// Start of function call - function invocation
    pub const FUNCTION: u32 = 131087;
    /// End of function call
    pub const FUNCTION_END: u32 = 131088;
    /// Start of function result - return value
    pub const RESULT: u32 = 131089;
    /// End of function result
    pub const RESULT_END: u32 = 131090;
    /// Start of error - error message
    pub const ERROR: u32 = 131091;
    /// End of error
    pub const ERROR_END: u32 = 131092;

    // Code Execution
    /// Start of code - inline code execution
    pub const CODE: u32 = 131093;
    /// End of code
    pub const CODE_END: u32 = 131094;
    /// Start of output - execution output
    pub const OUTPUT: u32 = 131095;
    /// End of output
    pub const OUTPUT_END: u32 = 131096;
    /// Start of language tag - code language
    pub const LANG: u32 = 131097;
    /// End of language tag
    pub const LANG_END: u32 = 131098;

    // RAG & Citations
    /// Start of context - retrieved context
    pub const CONTEXT: u32 = 131099;
    /// End of context
    pub const CONTEXT_END: u32 = 131100;
    /// Start of quote - exact citation
    pub const QUOTE: u32 = 131101;
    /// End of quote
    pub const QUOTE_END: u32 = 131102;
    /// Start of cite - citation reference
    pub const CITE: u32 = 131103;
    /// End of cite
    pub const CITE_END: u32 = 131104;
    /// Start of source - document source
    pub const SOURCE: u32 = 131105;
    /// End of source
    pub const SOURCE_END: u32 = 131106;

    // Memory/State Management
    /// Start of memory - persistent memory
    pub const MEMORY: u32 = 131107;
    /// End of memory
    pub const MEMORY_END: u32 = 131108;
    /// Start of recall - memory retrieval
    pub const RECALL: u32 = 131109;
    /// End of recall
    pub const RECALL_END: u32 = 131110;

    // Control Tokens
    /// Padding token
    pub const PAD: u32 = 131111;
    /// Stop generation token
    pub const STOP: u32 = 131112;
    /// Separator token
    pub const SEP: u32 = 131113;

    // Multimodal Placeholders
    /// Start of image - image placeholder
    pub const IMAGE: u32 = 131114;
    /// End of image
    pub const IMAGE_END: u32 = 131115;
    /// Start of audio - audio placeholder
    pub const AUDIO: u32 = 131116;
    /// End of audio
    pub const AUDIO_END: u32 = 131117;
    /// Start of video - video placeholder
    pub const VIDEO: u32 = 131118;
    /// End of video
    pub const VIDEO_END: u32 = 131119;

    // Document Structure
    /// Start of title - document/section title
    pub const TITLE: u32 = 131120;
    /// End of title
    pub const TITLE_END: u32 = 131121;
    /// Start of section - semantic document section
    pub const SECTION: u32 = 131122;
    /// End of section
    pub const SECTION_END: u32 = 131123;
    /// Start of summary - condensed content summary
    pub const SUMMARY: u32 = 131124;
    /// End of summary
    pub const SUMMARY_END: u32 = 131125;
}

/// Agent tokens for Qwen 2/3 (also Baichuan-M2).
///
/// The 54-token block starts at 151669. Every id here is also reachable
/// at runtime as `from_pretrained("qwen3")?.special_token_id(name)`;
/// these constants are the compile-time form, so a typo is a compile
/// error rather than a `None` to unwrap.
///
/// Qwen 2/3 (also Baichuan-M2) defines IM_END, IM_START itself, so those constants carry the
/// vocabulary's own id — below `base_vocab_size`, the id the checkpoint
/// was trained on — rather than a splintr-appended one.
///
/// The vocabulary's own markers are included too, so this module is its
/// whole special-token surface. A native name that would collide with
/// an agent token of the same meaning takes a `_NATIVE` suffix.
pub mod qwen3_agent_tokens {
    // Vocabulary-native tokens
    /// End of text marker
    pub const ENDOFTEXT: u32 = 151643;
    /// Native `<|im_start|>` - ChatML message start
    pub const IM_START: u32 = 151644;
    /// Native `<|im_end|>` - ChatML message end
    pub const IM_END: u32 = 151645;
    /// Object reference begin
    pub const OBJECT_REF_START: u32 = 151646;
    /// Object reference end
    pub const OBJECT_REF_END: u32 = 151647;
    /// Bounding box begin
    pub const BOX_START: u32 = 151648;
    /// Bounding box end
    pub const BOX_END: u32 = 151649;
    /// Quadrilateral begin
    pub const QUAD_START: u32 = 151650;
    /// Quadrilateral end
    pub const QUAD_END: u32 = 151651;
    /// Vision block begin
    pub const VISION_START: u32 = 151652;
    /// Vision block end
    pub const VISION_END: u32 = 151653;
    /// Vision padding
    pub const VISION_PAD: u32 = 151654;
    /// Image padding
    pub const IMAGE_PAD: u32 = 151655;
    /// Video padding
    pub const VIDEO_PAD: u32 = 151656;
    /// Native `<tool_call>`
    pub const TOOL_CALL: u32 = 151657;
    /// Native `</tool_call>`
    pub const TOOL_CALL_END: u32 = 151658;
    /// Fill-in-the-Middle prefix
    pub const FIM_PREFIX: u32 = 151659;
    /// Fill-in-the-Middle middle
    pub const FIM_MIDDLE: u32 = 151660;
    /// Fill-in-the-Middle suffix
    pub const FIM_SUFFIX: u32 = 151661;
    /// Fill-in-the-Middle padding
    pub const FIM_PAD: u32 = 151662;
    /// Repository name marker
    pub const REPO_NAME: u32 = 151663;
    /// File separator
    pub const FILE_SEP: u32 = 151664;
    /// Native `<tool_response>`
    pub const TOOL_RESPONSE: u32 = 151665;
    /// Native `</tool_response>`
    pub const TOOL_RESPONSE_END: u32 = 151666;
    /// Native `<think>` token
    pub const THINK_NATIVE: u32 = 151667;
    /// Native `</think>` token
    pub const THINK_END_NATIVE: u32 = 151668;

    // Conversation & Roles
    /// System role - system instructions
    pub const SYSTEM: u32 = 151669;
    /// User role - user input
    pub const USER: u32 = 151670;
    /// Assistant role - model output
    pub const ASSISTANT: u32 = 151671;

    // Reasoning/Thinking
    /// Start of thinking - Chain-of-Thought
    pub const THINK: u32 = 151674;
    /// End of thinking
    pub const THINK_END: u32 = 151675;

    // ReAct Agent Loop
    /// Start of plan - action planning
    pub const PLAN: u32 = 151676;
    /// End of plan
    pub const PLAN_END: u32 = 151677;
    /// Start of step - individual action step
    pub const STEP: u32 = 151678;
    /// End of step
    pub const STEP_END: u32 = 151679;
    /// Start of action - agent action
    pub const ACT: u32 = 151680;
    /// End of action
    pub const ACT_END: u32 = 151681;
    /// Start of observation - environment feedback
    pub const OBSERVE: u32 = 151682;
    /// End of observation
    pub const OBSERVE_END: u32 = 151683;

    // Tool/Function Calling
    /// Start of function call - function invocation
    pub const FUNCTION: u32 = 151684;
    /// End of function call
    pub const FUNCTION_END: u32 = 151685;
    /// Start of function result - return value
    pub const RESULT: u32 = 151686;
    /// End of function result
    pub const RESULT_END: u32 = 151687;
    /// Start of error - error message
    pub const ERROR: u32 = 151688;
    /// End of error
    pub const ERROR_END: u32 = 151689;

    // Code Execution
    /// Start of code - inline code execution
    pub const CODE: u32 = 151690;
    /// End of code
    pub const CODE_END: u32 = 151691;
    /// Start of output - execution output
    pub const OUTPUT: u32 = 151692;
    /// End of output
    pub const OUTPUT_END: u32 = 151693;
    /// Start of language tag - code language
    pub const LANG: u32 = 151694;
    /// End of language tag
    pub const LANG_END: u32 = 151695;

    // RAG & Citations
    /// Start of context - retrieved context
    pub const CONTEXT: u32 = 151696;
    /// End of context
    pub const CONTEXT_END: u32 = 151697;
    /// Start of quote - exact citation
    pub const QUOTE: u32 = 151698;
    /// End of quote
    pub const QUOTE_END: u32 = 151699;
    /// Start of cite - citation reference
    pub const CITE: u32 = 151700;
    /// End of cite
    pub const CITE_END: u32 = 151701;
    /// Start of source - document source
    pub const SOURCE: u32 = 151702;
    /// End of source
    pub const SOURCE_END: u32 = 151703;

    // Memory/State Management
    /// Start of memory - persistent memory
    pub const MEMORY: u32 = 151704;
    /// End of memory
    pub const MEMORY_END: u32 = 151705;
    /// Start of recall - memory retrieval
    pub const RECALL: u32 = 151706;
    /// End of recall
    pub const RECALL_END: u32 = 151707;

    // Control Tokens
    /// Padding token
    pub const PAD: u32 = 151708;
    /// Stop generation token
    pub const STOP: u32 = 151709;
    /// Separator token
    pub const SEP: u32 = 151710;

    // Multimodal Placeholders
    /// Start of image - image placeholder
    pub const IMAGE: u32 = 151711;
    /// End of image
    pub const IMAGE_END: u32 = 151712;
    /// Start of audio - audio placeholder
    pub const AUDIO: u32 = 151713;
    /// End of audio
    pub const AUDIO_END: u32 = 151714;
    /// Start of video - video placeholder
    pub const VIDEO: u32 = 151715;
    /// End of video
    pub const VIDEO_END: u32 = 151716;

    // Document Structure
    /// Start of title - document/section title
    pub const TITLE: u32 = 151717;
    /// End of title
    pub const TITLE_END: u32 = 151718;
    /// Start of section - semantic document section
    pub const SECTION: u32 = 151719;
    /// End of section
    pub const SECTION_END: u32 = 151720;
    /// Start of summary - condensed content summary
    pub const SUMMARY: u32 = 151721;
    /// End of summary
    pub const SUMMARY_END: u32 = 151722;
}

/// Agent tokens for GLM-4/4.5.
///
/// The 54-token block starts at 151365. Every id here is also reachable
/// at runtime as `from_pretrained("glm4")?.special_token_id(name)`;
/// these constants are the compile-time form, so a typo is a compile
/// error rather than a `None` to unwrap.
///
/// GLM-4/4.5 defines ASSISTANT, IMAGE, SYSTEM, USER, VIDEO itself, so those constants carry the
/// vocabulary's own id — below `base_vocab_size`, the id the checkpoint
/// was trained on — rather than a splintr-appended one.
///
/// The vocabulary's own markers are included too, so this module is its
/// whole special-token surface. A native name that would collide with
/// an agent token of the same meaning takes a `_NATIVE` suffix.
pub mod glm4_agent_tokens {
    // Vocabulary-native tokens
    /// End of text marker
    pub const ENDOFTEXT: u32 = 151329;
    /// `[MASK]`
    pub const MASK: u32 = 151330;
    /// `[gMASK]`
    pub const GMASK: u32 = 151331;
    /// `[sMASK]`
    pub const SMASK: u32 = 151332;
    /// Start of prefix `<sop>`
    pub const SOP: u32 = 151333;
    /// End of prefix `<eop>`
    pub const EOP: u32 = 151334;
    /// Native `<|system|>` role marker
    pub const SYSTEM: u32 = 151335;
    /// Native `<|user|>` role marker
    pub const USER: u32 = 151336;
    /// Native `<|assistant|>` role marker
    pub const ASSISTANT: u32 = 151337;
    /// Observation role marker
    pub const OBSERVATION: u32 = 151338;
    /// Image block begin
    pub const BEGIN_OF_IMAGE: u32 = 151339;
    /// Image block end
    pub const END_OF_IMAGE: u32 = 151340;
    /// Video block begin
    pub const BEGIN_OF_VIDEO: u32 = 151341;
    /// Video block end
    pub const END_OF_VIDEO: u32 = 151342;
    /// Audio block begin
    pub const BEGIN_OF_AUDIO: u32 = 151343;
    /// Audio block end
    pub const END_OF_AUDIO: u32 = 151344;
    /// Transcription begin
    pub const BEGIN_OF_TRANSCRIPTION: u32 = 151345;
    /// Transcription end
    pub const END_OF_TRANSCRIPTION: u32 = 151346;
    /// Code Fill-in-the-Middle prefix
    pub const CODE_PREFIX: u32 = 151347;
    /// Code Fill-in-the-Middle middle
    pub const CODE_MIDDLE: u32 = 151348;
    /// Code Fill-in-the-Middle suffix
    pub const CODE_SUFFIX: u32 = 151349;
    /// Native `<think>` token
    pub const THINK_NATIVE: u32 = 151350;
    /// Native `</think>` token
    pub const THINK_END_NATIVE: u32 = 151351;
    /// Native `<tool_call>`
    pub const TOOL_CALL: u32 = 151352;
    /// Native `</tool_call>`
    pub const TOOL_CALL_END: u32 = 151353;
    /// Native `<tool_response>`
    pub const TOOL_RESPONSE: u32 = 151354;
    /// Native `</tool_response>`
    pub const TOOL_RESPONSE_END: u32 = 151355;
    /// Tool argument key begin
    pub const ARG_KEY: u32 = 151356;
    /// Tool argument key end
    pub const ARG_KEY_END: u32 = 151357;
    /// Tool argument value begin
    pub const ARG_VALUE: u32 = 151358;
    /// Tool argument value end
    pub const ARG_VALUE_END: u32 = 151359;
    /// /nothink directive
    pub const NOTHINK: u32 = 151360;
    /// Box begin
    pub const BEGIN_OF_BOX: u32 = 151361;
    /// Box end
    pub const END_OF_BOX: u32 = 151362;
    /// Native `<|image|>` placeholder
    pub const IMAGE: u32 = 151363;
    /// Native `<|video|>` placeholder
    pub const VIDEO: u32 = 151364;

    // Conversation & Roles
    /// Start of message - ChatML wrapper
    pub const IM_START: u32 = 151368;
    /// End of message - ChatML wrapper
    pub const IM_END: u32 = 151369;

    // Reasoning/Thinking
    /// Start of thinking - Chain-of-Thought
    pub const THINK: u32 = 151370;
    /// End of thinking
    pub const THINK_END: u32 = 151371;

    // ReAct Agent Loop
    /// Start of plan - action planning
    pub const PLAN: u32 = 151372;
    /// End of plan
    pub const PLAN_END: u32 = 151373;
    /// Start of step - individual action step
    pub const STEP: u32 = 151374;
    /// End of step
    pub const STEP_END: u32 = 151375;
    /// Start of action - agent action
    pub const ACT: u32 = 151376;
    /// End of action
    pub const ACT_END: u32 = 151377;
    /// Start of observation - environment feedback
    pub const OBSERVE: u32 = 151378;
    /// End of observation
    pub const OBSERVE_END: u32 = 151379;

    // Tool/Function Calling
    /// Start of function call - function invocation
    pub const FUNCTION: u32 = 151380;
    /// End of function call
    pub const FUNCTION_END: u32 = 151381;
    /// Start of function result - return value
    pub const RESULT: u32 = 151382;
    /// End of function result
    pub const RESULT_END: u32 = 151383;
    /// Start of error - error message
    pub const ERROR: u32 = 151384;
    /// End of error
    pub const ERROR_END: u32 = 151385;

    // Code Execution
    /// Start of code - inline code execution
    pub const CODE: u32 = 151386;
    /// End of code
    pub const CODE_END: u32 = 151387;
    /// Start of output - execution output
    pub const OUTPUT: u32 = 151388;
    /// End of output
    pub const OUTPUT_END: u32 = 151389;
    /// Start of language tag - code language
    pub const LANG: u32 = 151390;
    /// End of language tag
    pub const LANG_END: u32 = 151391;

    // RAG & Citations
    /// Start of context - retrieved context
    pub const CONTEXT: u32 = 151392;
    /// End of context
    pub const CONTEXT_END: u32 = 151393;
    /// Start of quote - exact citation
    pub const QUOTE: u32 = 151394;
    /// End of quote
    pub const QUOTE_END: u32 = 151395;
    /// Start of cite - citation reference
    pub const CITE: u32 = 151396;
    /// End of cite
    pub const CITE_END: u32 = 151397;
    /// Start of source - document source
    pub const SOURCE: u32 = 151398;
    /// End of source
    pub const SOURCE_END: u32 = 151399;

    // Memory/State Management
    /// Start of memory - persistent memory
    pub const MEMORY: u32 = 151400;
    /// End of memory
    pub const MEMORY_END: u32 = 151401;
    /// Start of recall - memory retrieval
    pub const RECALL: u32 = 151402;
    /// End of recall
    pub const RECALL_END: u32 = 151403;

    // Control Tokens
    /// Padding token
    pub const PAD: u32 = 151404;
    /// Stop generation token
    pub const STOP: u32 = 151405;
    /// Separator token
    pub const SEP: u32 = 151406;

    // Multimodal Placeholders
    /// End of image
    pub const IMAGE_END: u32 = 151408;
    /// Start of audio - audio placeholder
    pub const AUDIO: u32 = 151409;
    /// End of audio
    pub const AUDIO_END: u32 = 151410;
    /// End of video
    pub const VIDEO_END: u32 = 151412;

    // Document Structure
    /// Start of title - document/section title
    pub const TITLE: u32 = 151413;
    /// End of title
    pub const TITLE_END: u32 = 151414;
    /// Start of section - semantic document section
    pub const SECTION: u32 = 151415;
    /// End of section
    pub const SECTION_END: u32 = 151416;
    /// Start of summary - condensed content summary
    pub const SUMMARY: u32 = 151417;
    /// End of summary
    pub const SUMMARY_END: u32 = 151418;
}

/// Agent tokens for OpenAI gpt-oss.
///
/// The 54-token block starts at 200019. Every id here is also reachable
/// at runtime as `from_pretrained("gpt-oss")?.special_token_id(name)`;
/// these constants are the compile-time form, so a typo is a compile
/// error rather than a `None` to unwrap.
///
/// The vocabulary's own markers are included too, so this module is its
/// whole special-token surface. A native name that would collide with
/// an agent token of the same meaning takes a `_NATIVE` suffix.
pub mod gpt_oss_agent_tokens {
    // Vocabulary-native tokens
    /// Start of text marker
    pub const STARTOFTEXT: u32 = 199998;
    /// End of text marker
    pub const ENDOFTEXT: u32 = 199999;
    /// End of a final assistant turn
    pub const RETURN: u32 = 200002;
    /// Constrained-output marker
    pub const CONSTRAIN: u32 = 200003;
    /// Channel marker (analysis/commentary/final)
    pub const CHANNEL: u32 = 200005;
    /// Message start
    pub const START: u32 = 200006;
    /// Message end
    pub const END: u32 = 200007;
    /// Message body begin
    pub const MESSAGE: u32 = 200008;
    /// Tool call marker
    pub const CALL: u32 = 200012;
    /// End of prompt
    pub const ENDOFPROMPT: u32 = 200018;

    // Conversation & Roles
    /// System role - system instructions
    pub const SYSTEM: u32 = 200019;
    /// User role - user input
    pub const USER: u32 = 200020;
    /// Assistant role - model output
    pub const ASSISTANT: u32 = 200021;
    /// Start of message - ChatML wrapper
    pub const IM_START: u32 = 200022;
    /// End of message - ChatML wrapper
    pub const IM_END: u32 = 200023;

    // Reasoning/Thinking
    /// Start of thinking - Chain-of-Thought
    pub const THINK: u32 = 200024;
    /// End of thinking
    pub const THINK_END: u32 = 200025;

    // ReAct Agent Loop
    /// Start of plan - action planning
    pub const PLAN: u32 = 200026;
    /// End of plan
    pub const PLAN_END: u32 = 200027;
    /// Start of step - individual action step
    pub const STEP: u32 = 200028;
    /// End of step
    pub const STEP_END: u32 = 200029;
    /// Start of action - agent action
    pub const ACT: u32 = 200030;
    /// End of action
    pub const ACT_END: u32 = 200031;
    /// Start of observation - environment feedback
    pub const OBSERVE: u32 = 200032;
    /// End of observation
    pub const OBSERVE_END: u32 = 200033;

    // Tool/Function Calling
    /// Start of function call - function invocation
    pub const FUNCTION: u32 = 200034;
    /// End of function call
    pub const FUNCTION_END: u32 = 200035;
    /// Start of function result - return value
    pub const RESULT: u32 = 200036;
    /// End of function result
    pub const RESULT_END: u32 = 200037;
    /// Start of error - error message
    pub const ERROR: u32 = 200038;
    /// End of error
    pub const ERROR_END: u32 = 200039;

    // Code Execution
    /// Start of code - inline code execution
    pub const CODE: u32 = 200040;
    /// End of code
    pub const CODE_END: u32 = 200041;
    /// Start of output - execution output
    pub const OUTPUT: u32 = 200042;
    /// End of output
    pub const OUTPUT_END: u32 = 200043;
    /// Start of language tag - code language
    pub const LANG: u32 = 200044;
    /// End of language tag
    pub const LANG_END: u32 = 200045;

    // RAG & Citations
    /// Start of context - retrieved context
    pub const CONTEXT: u32 = 200046;
    /// End of context
    pub const CONTEXT_END: u32 = 200047;
    /// Start of quote - exact citation
    pub const QUOTE: u32 = 200048;
    /// End of quote
    pub const QUOTE_END: u32 = 200049;
    /// Start of cite - citation reference
    pub const CITE: u32 = 200050;
    /// End of cite
    pub const CITE_END: u32 = 200051;
    /// Start of source - document source
    pub const SOURCE: u32 = 200052;
    /// End of source
    pub const SOURCE_END: u32 = 200053;

    // Memory/State Management
    /// Start of memory - persistent memory
    pub const MEMORY: u32 = 200054;
    /// End of memory
    pub const MEMORY_END: u32 = 200055;
    /// Start of recall - memory retrieval
    pub const RECALL: u32 = 200056;
    /// End of recall
    pub const RECALL_END: u32 = 200057;

    // Control Tokens
    /// Padding token
    pub const PAD: u32 = 200058;
    /// Stop generation token
    pub const STOP: u32 = 200059;
    /// Separator token
    pub const SEP: u32 = 200060;

    // Multimodal Placeholders
    /// Start of image - image placeholder
    pub const IMAGE: u32 = 200061;
    /// End of image
    pub const IMAGE_END: u32 = 200062;
    /// Start of audio - audio placeholder
    pub const AUDIO: u32 = 200063;
    /// End of audio
    pub const AUDIO_END: u32 = 200064;
    /// Start of video - video placeholder
    pub const VIDEO: u32 = 200065;
    /// End of video
    pub const VIDEO_END: u32 = 200066;

    // Document Structure
    /// Start of title - document/section title
    pub const TITLE: u32 = 200067;
    /// End of title
    pub const TITLE_END: u32 = 200068;
    /// Start of section - semantic document section
    pub const SECTION: u32 = 200069;
    /// End of section
    pub const SECTION_END: u32 = 200070;
    /// Start of summary - condensed content summary
    pub const SUMMARY: u32 = 200071;
    /// End of summary
    pub const SUMMARY_END: u32 = 200072;
}

/// Agent tokens for Kimi K2 (K2, K2.5, K2.6, K2.7, Kimi-Linear).
///
/// The 54-token block starts at 163840. Every id here is also reachable
/// at runtime as `from_pretrained("kimi_k2")?.special_token_id(name)`;
/// these constants are the compile-time form, so a typo is a compile
/// error rather than a `None` to unwrap.
///
/// Kimi K2 (K2, K2.5, K2.6, K2.7, Kimi-Linear) defines IM_END itself, so those constants carry the
/// vocabulary's own id — below `base_vocab_size`, the id the checkpoint
/// was trained on — rather than a splintr-appended one.
///
/// The vocabulary's own markers are included too, so this module is its
/// whole special-token surface. A native name that would collide with
/// an agent token of the same meaning takes a `_NATIVE` suffix.
pub mod kimi_k2_agent_tokens {
    // Vocabulary-native tokens
    /// Beginning of sequence `[BOS]`
    pub const BOS: u32 = 163584;
    /// End of sequence `[EOS]`
    pub const EOS: u32 = 163585;
    /// Native `<|im_end|>` - end of message
    pub const IM_END: u32 = 163586;
    /// User turn marker
    pub const IM_USER: u32 = 163587;
    /// Assistant turn marker
    pub const IM_ASSISTANT: u32 = 163588;
    /// Header begin
    pub const START_HEADER_ID: u32 = 163590;
    /// Header end
    pub const END_HEADER_ID: u32 = 163591;
    /// End of turn `[EOT]`
    pub const EOT: u32 = 163593;
    /// System turn marker
    pub const IM_SYSTEM: u32 = 163594;
    /// Tool calls section begin
    pub const TOOL_CALLS_SECTION_BEGIN: u32 = 163595;
    /// Tool calls section end
    pub const TOOL_CALLS_SECTION_END: u32 = 163596;
    /// Single tool call begin
    pub const TOOL_CALL_BEGIN: u32 = 163597;
    /// Tool call argument begin
    pub const TOOL_CALL_ARGUMENT_BEGIN: u32 = 163598;
    /// Single tool call end
    pub const TOOL_CALL_END: u32 = 163599;
    /// Message middle marker
    pub const IM_MIDDLE: u32 = 163601;
    /// Media block begin
    pub const MEDIA_BEGIN: u32 = 163602;
    /// Media content
    pub const MEDIA_CONTENT: u32 = 163603;
    /// Media block end
    pub const MEDIA_END: u32 = 163604;
    /// Media padding
    pub const MEDIA_PAD: u32 = 163605;
    /// Native `<think>` token
    pub const THINK_NATIVE: u32 = 163606;
    /// Native `</think>` token
    pub const THINK_END_NATIVE: u32 = 163607;
    /// Unknown token `[UNK]`
    pub const UNK: u32 = 163838;
    /// Native padding `[PAD]`
    pub const PAD_NATIVE: u32 = 163839;

    // Conversation & Roles
    /// System role - system instructions
    pub const SYSTEM: u32 = 163840;
    /// User role - user input
    pub const USER: u32 = 163841;
    /// Assistant role - model output
    pub const ASSISTANT: u32 = 163842;
    /// Start of message - ChatML wrapper
    pub const IM_START: u32 = 163843;

    // Reasoning/Thinking
    /// Start of thinking - Chain-of-Thought
    pub const THINK: u32 = 163845;
    /// End of thinking
    pub const THINK_END: u32 = 163846;

    // ReAct Agent Loop
    /// Start of plan - action planning
    pub const PLAN: u32 = 163847;
    /// End of plan
    pub const PLAN_END: u32 = 163848;
    /// Start of step - individual action step
    pub const STEP: u32 = 163849;
    /// End of step
    pub const STEP_END: u32 = 163850;
    /// Start of action - agent action
    pub const ACT: u32 = 163851;
    /// End of action
    pub const ACT_END: u32 = 163852;
    /// Start of observation - environment feedback
    pub const OBSERVE: u32 = 163853;
    /// End of observation
    pub const OBSERVE_END: u32 = 163854;

    // Tool/Function Calling
    /// Start of function call - function invocation
    pub const FUNCTION: u32 = 163855;
    /// End of function call
    pub const FUNCTION_END: u32 = 163856;
    /// Start of function result - return value
    pub const RESULT: u32 = 163857;
    /// End of function result
    pub const RESULT_END: u32 = 163858;
    /// Start of error - error message
    pub const ERROR: u32 = 163859;
    /// End of error
    pub const ERROR_END: u32 = 163860;

    // Code Execution
    /// Start of code - inline code execution
    pub const CODE: u32 = 163861;
    /// End of code
    pub const CODE_END: u32 = 163862;
    /// Start of output - execution output
    pub const OUTPUT: u32 = 163863;
    /// End of output
    pub const OUTPUT_END: u32 = 163864;
    /// Start of language tag - code language
    pub const LANG: u32 = 163865;
    /// End of language tag
    pub const LANG_END: u32 = 163866;

    // RAG & Citations
    /// Start of context - retrieved context
    pub const CONTEXT: u32 = 163867;
    /// End of context
    pub const CONTEXT_END: u32 = 163868;
    /// Start of quote - exact citation
    pub const QUOTE: u32 = 163869;
    /// End of quote
    pub const QUOTE_END: u32 = 163870;
    /// Start of cite - citation reference
    pub const CITE: u32 = 163871;
    /// End of cite
    pub const CITE_END: u32 = 163872;
    /// Start of source - document source
    pub const SOURCE: u32 = 163873;
    /// End of source
    pub const SOURCE_END: u32 = 163874;

    // Memory/State Management
    /// Start of memory - persistent memory
    pub const MEMORY: u32 = 163875;
    /// End of memory
    pub const MEMORY_END: u32 = 163876;
    /// Start of recall - memory retrieval
    pub const RECALL: u32 = 163877;
    /// End of recall
    pub const RECALL_END: u32 = 163878;

    // Control Tokens
    /// Padding token
    pub const PAD: u32 = 163879;
    /// Stop generation token
    pub const STOP: u32 = 163880;
    /// Separator token
    pub const SEP: u32 = 163881;

    // Multimodal Placeholders
    /// Start of image - image placeholder
    pub const IMAGE: u32 = 163882;
    /// End of image
    pub const IMAGE_END: u32 = 163883;
    /// Start of audio - audio placeholder
    pub const AUDIO: u32 = 163884;
    /// End of audio
    pub const AUDIO_END: u32 = 163885;
    /// Start of video - video placeholder
    pub const VIDEO: u32 = 163886;
    /// End of video
    pub const VIDEO_END: u32 = 163887;

    // Document Structure
    /// Start of title - document/section title
    pub const TITLE: u32 = 163888;
    /// End of title
    pub const TITLE_END: u32 = 163889;
    /// Start of section - semantic document section
    pub const SECTION: u32 = 163890;
    /// End of section
    pub const SECTION_END: u32 = 163891;
    /// Start of summary - condensed content summary
    pub const SUMMARY: u32 = 163892;
    /// End of summary
    pub const SUMMARY_END: u32 = 163893;
}

/// Agent tokens for Kimi K3.
///
/// The 54-token block starts at 163840. Every id here is also reachable
/// at runtime as `from_pretrained("kimi_k3")?.special_token_id(name)`;
/// these constants are the compile-time form, so a typo is a compile
/// error rather than a `None` to unwrap.
///
/// Kimi K3 defines SEP itself, so those constants carry the
/// vocabulary's own id — below `base_vocab_size`, the id the checkpoint
/// was trained on — rather than a splintr-appended one.
///
/// The vocabulary's own markers are included too, so this module is its
/// whole special-token surface. A native name that would collide with
/// an agent token of the same meaning takes a `_NATIVE` suffix.
pub mod kimi_k3_agent_tokens {
    // Vocabulary-native tokens
    /// Beginning of sequence `[BOS]`
    pub const BOS: u32 = 163584;
    /// End of sequence `[EOS]`
    pub const EOS: u32 = 163585;
    /// End of message
    pub const END_OF_MSG: u32 = 163586;
    /// Open marker
    pub const OPEN: u32 = 163587;
    /// Close marker
    pub const CLOSE: u32 = 163588;
    /// Separator
    pub const SEP: u32 = 163589;
    /// Header begin
    pub const START_HEADER_ID: u32 = 163590;
    /// Header end
    pub const END_HEADER_ID: u32 = 163591;
    /// End of turn `[EOT]`
    pub const EOT: u32 = 163593;
    /// Media block begin
    pub const MEDIA_BEGIN: u32 = 163602;
    /// Media content
    pub const MEDIA_CONTENT: u32 = 163603;
    /// Media block end
    pub const MEDIA_END: u32 = 163604;
    /// Media padding
    pub const MEDIA_PAD: u32 = 163605;
    /// OS-agent mode marker
    pub const OSAGENT_MODE: u32 = 163649;
    /// Unknown token `[UNK]`
    pub const UNK: u32 = 163838;
    /// Native padding `[PAD]`
    pub const PAD_NATIVE: u32 = 163839;

    // Conversation & Roles
    /// System role - system instructions
    pub const SYSTEM: u32 = 163840;
    /// User role - user input
    pub const USER: u32 = 163841;
    /// Assistant role - model output
    pub const ASSISTANT: u32 = 163842;
    /// Start of message - ChatML wrapper
    pub const IM_START: u32 = 163843;
    /// End of message - ChatML wrapper
    pub const IM_END: u32 = 163844;

    // Reasoning/Thinking
    /// Start of thinking - Chain-of-Thought
    pub const THINK: u32 = 163845;
    /// End of thinking
    pub const THINK_END: u32 = 163846;

    // ReAct Agent Loop
    /// Start of plan - action planning
    pub const PLAN: u32 = 163847;
    /// End of plan
    pub const PLAN_END: u32 = 163848;
    /// Start of step - individual action step
    pub const STEP: u32 = 163849;
    /// End of step
    pub const STEP_END: u32 = 163850;
    /// Start of action - agent action
    pub const ACT: u32 = 163851;
    /// End of action
    pub const ACT_END: u32 = 163852;
    /// Start of observation - environment feedback
    pub const OBSERVE: u32 = 163853;
    /// End of observation
    pub const OBSERVE_END: u32 = 163854;

    // Tool/Function Calling
    /// Start of function call - function invocation
    pub const FUNCTION: u32 = 163855;
    /// End of function call
    pub const FUNCTION_END: u32 = 163856;
    /// Start of function result - return value
    pub const RESULT: u32 = 163857;
    /// End of function result
    pub const RESULT_END: u32 = 163858;
    /// Start of error - error message
    pub const ERROR: u32 = 163859;
    /// End of error
    pub const ERROR_END: u32 = 163860;

    // Code Execution
    /// Start of code - inline code execution
    pub const CODE: u32 = 163861;
    /// End of code
    pub const CODE_END: u32 = 163862;
    /// Start of output - execution output
    pub const OUTPUT: u32 = 163863;
    /// End of output
    pub const OUTPUT_END: u32 = 163864;
    /// Start of language tag - code language
    pub const LANG: u32 = 163865;
    /// End of language tag
    pub const LANG_END: u32 = 163866;

    // RAG & Citations
    /// Start of context - retrieved context
    pub const CONTEXT: u32 = 163867;
    /// End of context
    pub const CONTEXT_END: u32 = 163868;
    /// Start of quote - exact citation
    pub const QUOTE: u32 = 163869;
    /// End of quote
    pub const QUOTE_END: u32 = 163870;
    /// Start of cite - citation reference
    pub const CITE: u32 = 163871;
    /// End of cite
    pub const CITE_END: u32 = 163872;
    /// Start of source - document source
    pub const SOURCE: u32 = 163873;
    /// End of source
    pub const SOURCE_END: u32 = 163874;

    // Memory/State Management
    /// Start of memory - persistent memory
    pub const MEMORY: u32 = 163875;
    /// End of memory
    pub const MEMORY_END: u32 = 163876;
    /// Start of recall - memory retrieval
    pub const RECALL: u32 = 163877;
    /// End of recall
    pub const RECALL_END: u32 = 163878;

    // Control Tokens
    /// Padding token
    pub const PAD: u32 = 163879;
    /// Stop generation token
    pub const STOP: u32 = 163880;

    // Multimodal Placeholders
    /// Start of image - image placeholder
    pub const IMAGE: u32 = 163882;
    /// End of image
    pub const IMAGE_END: u32 = 163883;
    /// Start of audio - audio placeholder
    pub const AUDIO: u32 = 163884;
    /// End of audio
    pub const AUDIO_END: u32 = 163885;
    /// Start of video - video placeholder
    pub const VIDEO: u32 = 163886;
    /// End of video
    pub const VIDEO_END: u32 = 163887;

    // Document Structure
    /// Start of title - document/section title
    pub const TITLE: u32 = 163888;
    /// End of title
    pub const TITLE_END: u32 = 163889;
    /// Start of section - semantic document section
    pub const SECTION: u32 = 163890;
    /// End of section
    pub const SECTION_END: u32 = 163891;
    /// Start of summary - condensed content summary
    pub const SUMMARY: u32 = 163892;
    /// End of summary
    pub const SUMMARY_END: u32 = 163893;
}

/// Agent tokens for Microsoft Phi-4.
///
/// The 54-token block starts at 100352. Every id here is also reachable
/// at runtime as `from_pretrained("phi4")?.special_token_id(name)`;
/// these constants are the compile-time form, so a typo is a compile
/// error rather than a `None` to unwrap.
///
/// Microsoft Phi-4 defines IM_END, IM_START itself, so those constants carry the
/// vocabulary's own id — below `base_vocab_size`, the id the checkpoint
/// was trained on — rather than a splintr-appended one.
///
/// The vocabulary's own markers are included too, so this module is its
/// whole special-token surface. A native name that would collide with
/// an agent token of the same meaning takes a `_NATIVE` suffix.
pub mod phi4_agent_tokens {
    // Vocabulary-native tokens
    /// End of text marker
    pub const ENDOFTEXT: u32 = 100257;
    /// Fill-in-the-Middle prefix
    pub const FIM_PREFIX: u32 = 100258;
    /// Fill-in-the-Middle middle
    pub const FIM_MIDDLE: u32 = 100259;
    /// Fill-in-the-Middle suffix
    pub const FIM_SUFFIX: u32 = 100260;
    /// Native `<|im_start|>` - ChatML message start
    pub const IM_START: u32 = 100264;
    /// Native `<|im_end|>` - ChatML message end
    pub const IM_END: u32 = 100265;
    /// Native `<|im_sep|>` - ChatML role/content separator
    pub const IM_SEP: u32 = 100266;
    /// End of prompt marker
    pub const ENDOFPROMPT: u32 = 100276;

    // Conversation & Roles
    /// System role - system instructions
    pub const SYSTEM: u32 = 100352;
    /// User role - user input
    pub const USER: u32 = 100353;
    /// Assistant role - model output
    pub const ASSISTANT: u32 = 100354;

    // Reasoning/Thinking
    /// Start of thinking - Chain-of-Thought
    pub const THINK: u32 = 100357;
    /// End of thinking
    pub const THINK_END: u32 = 100358;

    // ReAct Agent Loop
    /// Start of plan - action planning
    pub const PLAN: u32 = 100359;
    /// End of plan
    pub const PLAN_END: u32 = 100360;
    /// Start of step - individual action step
    pub const STEP: u32 = 100361;
    /// End of step
    pub const STEP_END: u32 = 100362;
    /// Start of action - agent action
    pub const ACT: u32 = 100363;
    /// End of action
    pub const ACT_END: u32 = 100364;
    /// Start of observation - environment feedback
    pub const OBSERVE: u32 = 100365;
    /// End of observation
    pub const OBSERVE_END: u32 = 100366;

    // Tool/Function Calling
    /// Start of function call - function invocation
    pub const FUNCTION: u32 = 100367;
    /// End of function call
    pub const FUNCTION_END: u32 = 100368;
    /// Start of function result - return value
    pub const RESULT: u32 = 100369;
    /// End of function result
    pub const RESULT_END: u32 = 100370;
    /// Start of error - error message
    pub const ERROR: u32 = 100371;
    /// End of error
    pub const ERROR_END: u32 = 100372;

    // Code Execution
    /// Start of code - inline code execution
    pub const CODE: u32 = 100373;
    /// End of code
    pub const CODE_END: u32 = 100374;
    /// Start of output - execution output
    pub const OUTPUT: u32 = 100375;
    /// End of output
    pub const OUTPUT_END: u32 = 100376;
    /// Start of language tag - code language
    pub const LANG: u32 = 100377;
    /// End of language tag
    pub const LANG_END: u32 = 100378;

    // RAG & Citations
    /// Start of context - retrieved context
    pub const CONTEXT: u32 = 100379;
    /// End of context
    pub const CONTEXT_END: u32 = 100380;
    /// Start of quote - exact citation
    pub const QUOTE: u32 = 100381;
    /// End of quote
    pub const QUOTE_END: u32 = 100382;
    /// Start of cite - citation reference
    pub const CITE: u32 = 100383;
    /// End of cite
    pub const CITE_END: u32 = 100384;
    /// Start of source - document source
    pub const SOURCE: u32 = 100385;
    /// End of source
    pub const SOURCE_END: u32 = 100386;

    // Memory/State Management
    /// Start of memory - persistent memory
    pub const MEMORY: u32 = 100387;
    /// End of memory
    pub const MEMORY_END: u32 = 100388;
    /// Start of recall - memory retrieval
    pub const RECALL: u32 = 100389;
    /// End of recall
    pub const RECALL_END: u32 = 100390;

    // Control Tokens
    /// Padding token
    pub const PAD: u32 = 100391;
    /// Stop generation token
    pub const STOP: u32 = 100392;
    /// Separator token
    pub const SEP: u32 = 100393;

    // Multimodal Placeholders
    /// Start of image - image placeholder
    pub const IMAGE: u32 = 100394;
    /// End of image
    pub const IMAGE_END: u32 = 100395;
    /// Start of audio - audio placeholder
    pub const AUDIO: u32 = 100396;
    /// End of audio
    pub const AUDIO_END: u32 = 100397;
    /// Start of video - video placeholder
    pub const VIDEO: u32 = 100398;
    /// End of video
    pub const VIDEO_END: u32 = 100399;

    // Document Structure
    /// Start of title - document/section title
    pub const TITLE: u32 = 100400;
    /// End of title
    pub const TITLE_END: u32 = 100401;
    /// Start of section - semantic document section
    pub const SECTION: u32 = 100402;
    /// End of section
    pub const SECTION_END: u32 = 100403;
    /// Start of summary - condensed content summary
    pub const SUMMARY: u32 = 100404;
    /// End of summary
    pub const SUMMARY_END: u32 = 100405;
}

/// Agent tokens for AI2 OLMo-2.
///
/// The 54-token block starts at 100278. Every id here is also reachable
/// at runtime as `from_pretrained("olmo2")?.special_token_id(name)`;
/// these constants are the compile-time form, so a typo is a compile
/// error rather than a `None` to unwrap.
///
/// AI2 OLMo-2 defines IM_END, IM_START, PAD itself, so those constants carry the
/// vocabulary's own id — below `base_vocab_size`, the id the checkpoint
/// was trained on — rather than a splintr-appended one.
///
/// The vocabulary's own markers are included too, so this module is its
/// whole special-token surface. A native name that would collide with
/// an agent token of the same meaning takes a `_NATIVE` suffix.
pub mod olmo2_agent_tokens {
    // Vocabulary-native tokens
    /// Reserved slot 0
    pub const EXTRA_ID_0: u32 = 100256;
    /// End of text marker
    pub const ENDOFTEXT: u32 = 100257;
    /// Fill-in-the-Middle prefix
    pub const FIM_PREFIX: u32 = 100258;
    /// Fill-in-the-Middle middle
    pub const FIM_MIDDLE: u32 = 100259;
    /// Fill-in-the-Middle suffix
    pub const FIM_SUFFIX: u32 = 100260;
    /// PII placeholder |||PHONE_NUMBER|||
    pub const PHONE_NUMBER: u32 = 100261;
    /// PII placeholder |||EMAIL_ADDRESS|||
    pub const EMAIL_ADDRESS: u32 = 100262;
    /// PII placeholder |||IP_ADDRESS|||
    pub const IP_ADDRESS: u32 = 100263;
    /// Native `<|im_start|>` - ChatML message start
    pub const IM_START: u32 = 100264;
    /// Native `<|im_end|>` - ChatML message end
    pub const IM_END: u32 = 100265;
    /// Reserved slot 1
    pub const EXTRA_ID_1: u32 = 100266;
    /// Reserved slot 2
    pub const EXTRA_ID_2: u32 = 100267;
    /// Reserved slot 3
    pub const EXTRA_ID_3: u32 = 100268;
    /// Reserved slot 4
    pub const EXTRA_ID_4: u32 = 100269;
    /// Reserved slot 5
    pub const EXTRA_ID_5: u32 = 100270;
    /// Reserved slot 6
    pub const EXTRA_ID_6: u32 = 100271;
    /// Reserved slot 7
    pub const EXTRA_ID_7: u32 = 100272;
    /// Reserved slot 8
    pub const EXTRA_ID_8: u32 = 100273;
    /// Reserved slot 9
    pub const EXTRA_ID_9: u32 = 100274;
    /// Reserved slot 10
    pub const EXTRA_ID_10: u32 = 100275;
    /// End of prompt marker
    pub const ENDOFPROMPT: u32 = 100276;
    /// Native `<|pad|>` - padding
    pub const PAD: u32 = 100277;

    // Conversation & Roles
    /// System role - system instructions
    pub const SYSTEM: u32 = 100278;
    /// User role - user input
    pub const USER: u32 = 100279;
    /// Assistant role - model output
    pub const ASSISTANT: u32 = 100280;

    // Reasoning/Thinking
    /// Start of thinking - Chain-of-Thought
    pub const THINK: u32 = 100283;
    /// End of thinking
    pub const THINK_END: u32 = 100284;

    // ReAct Agent Loop
    /// Start of plan - action planning
    pub const PLAN: u32 = 100285;
    /// End of plan
    pub const PLAN_END: u32 = 100286;
    /// Start of step - individual action step
    pub const STEP: u32 = 100287;
    /// End of step
    pub const STEP_END: u32 = 100288;
    /// Start of action - agent action
    pub const ACT: u32 = 100289;
    /// End of action
    pub const ACT_END: u32 = 100290;
    /// Start of observation - environment feedback
    pub const OBSERVE: u32 = 100291;
    /// End of observation
    pub const OBSERVE_END: u32 = 100292;

    // Tool/Function Calling
    /// Start of function call - function invocation
    pub const FUNCTION: u32 = 100293;
    /// End of function call
    pub const FUNCTION_END: u32 = 100294;
    /// Start of function result - return value
    pub const RESULT: u32 = 100295;
    /// End of function result
    pub const RESULT_END: u32 = 100296;
    /// Start of error - error message
    pub const ERROR: u32 = 100297;
    /// End of error
    pub const ERROR_END: u32 = 100298;

    // Code Execution
    /// Start of code - inline code execution
    pub const CODE: u32 = 100299;
    /// End of code
    pub const CODE_END: u32 = 100300;
    /// Start of output - execution output
    pub const OUTPUT: u32 = 100301;
    /// End of output
    pub const OUTPUT_END: u32 = 100302;
    /// Start of language tag - code language
    pub const LANG: u32 = 100303;
    /// End of language tag
    pub const LANG_END: u32 = 100304;

    // RAG & Citations
    /// Start of context - retrieved context
    pub const CONTEXT: u32 = 100305;
    /// End of context
    pub const CONTEXT_END: u32 = 100306;
    /// Start of quote - exact citation
    pub const QUOTE: u32 = 100307;
    /// End of quote
    pub const QUOTE_END: u32 = 100308;
    /// Start of cite - citation reference
    pub const CITE: u32 = 100309;
    /// End of cite
    pub const CITE_END: u32 = 100310;
    /// Start of source - document source
    pub const SOURCE: u32 = 100311;
    /// End of source
    pub const SOURCE_END: u32 = 100312;

    // Memory/State Management
    /// Start of memory - persistent memory
    pub const MEMORY: u32 = 100313;
    /// End of memory
    pub const MEMORY_END: u32 = 100314;
    /// Start of recall - memory retrieval
    pub const RECALL: u32 = 100315;
    /// End of recall
    pub const RECALL_END: u32 = 100316;

    // Control Tokens
    /// Stop generation token
    pub const STOP: u32 = 100318;
    /// Separator token
    pub const SEP: u32 = 100319;

    // Multimodal Placeholders
    /// Start of image - image placeholder
    pub const IMAGE: u32 = 100320;
    /// End of image
    pub const IMAGE_END: u32 = 100321;
    /// Start of audio - audio placeholder
    pub const AUDIO: u32 = 100322;
    /// End of audio
    pub const AUDIO_END: u32 = 100323;
    /// Start of video - video placeholder
    pub const VIDEO: u32 = 100324;
    /// End of video
    pub const VIDEO_END: u32 = 100325;

    // Document Structure
    /// Start of title - document/section title
    pub const TITLE: u32 = 100326;
    /// End of title
    pub const TITLE_END: u32 = 100327;
    /// Start of section - semantic document section
    pub const SECTION: u32 = 100328;
    /// End of section
    pub const SECTION_END: u32 = 100329;
    /// Start of summary - condensed content summary
    pub const SUMMARY: u32 = 100330;
    /// End of summary
    pub const SUMMARY_END: u32 = 100331;
}

/// Agent tokens for Llama 2 (also TinyLlama, Vicuna).
///
/// The 54-token block starts at 32000. Every id here is also reachable
/// at runtime as `from_pretrained("llama2")?.special_token_id(name)`;
/// these constants are the compile-time form, so a typo is a compile
/// error rather than a `None` to unwrap.
pub mod llama2_agent_tokens {
    // Conversation & Roles
    /// System role - system instructions
    pub const SYSTEM: u32 = 32000;
    /// User role - user input
    pub const USER: u32 = 32001;
    /// Assistant role - model output
    pub const ASSISTANT: u32 = 32002;
    /// Start of message - ChatML wrapper
    pub const IM_START: u32 = 32003;
    /// End of message - ChatML wrapper
    pub const IM_END: u32 = 32004;

    // Reasoning/Thinking
    /// Start of thinking - Chain-of-Thought
    pub const THINK: u32 = 32005;
    /// End of thinking
    pub const THINK_END: u32 = 32006;

    // ReAct Agent Loop
    /// Start of plan - action planning
    pub const PLAN: u32 = 32007;
    /// End of plan
    pub const PLAN_END: u32 = 32008;
    /// Start of step - individual action step
    pub const STEP: u32 = 32009;
    /// End of step
    pub const STEP_END: u32 = 32010;
    /// Start of action - agent action
    pub const ACT: u32 = 32011;
    /// End of action
    pub const ACT_END: u32 = 32012;
    /// Start of observation - environment feedback
    pub const OBSERVE: u32 = 32013;
    /// End of observation
    pub const OBSERVE_END: u32 = 32014;

    // Tool/Function Calling
    /// Start of function call - function invocation
    pub const FUNCTION: u32 = 32015;
    /// End of function call
    pub const FUNCTION_END: u32 = 32016;
    /// Start of function result - return value
    pub const RESULT: u32 = 32017;
    /// End of function result
    pub const RESULT_END: u32 = 32018;
    /// Start of error - error message
    pub const ERROR: u32 = 32019;
    /// End of error
    pub const ERROR_END: u32 = 32020;

    // Code Execution
    /// Start of code - inline code execution
    pub const CODE: u32 = 32021;
    /// End of code
    pub const CODE_END: u32 = 32022;
    /// Start of output - execution output
    pub const OUTPUT: u32 = 32023;
    /// End of output
    pub const OUTPUT_END: u32 = 32024;
    /// Start of language tag - code language
    pub const LANG: u32 = 32025;
    /// End of language tag
    pub const LANG_END: u32 = 32026;

    // RAG & Citations
    /// Start of context - retrieved context
    pub const CONTEXT: u32 = 32027;
    /// End of context
    pub const CONTEXT_END: u32 = 32028;
    /// Start of quote - exact citation
    pub const QUOTE: u32 = 32029;
    /// End of quote
    pub const QUOTE_END: u32 = 32030;
    /// Start of cite - citation reference
    pub const CITE: u32 = 32031;
    /// End of cite
    pub const CITE_END: u32 = 32032;
    /// Start of source - document source
    pub const SOURCE: u32 = 32033;
    /// End of source
    pub const SOURCE_END: u32 = 32034;

    // Memory/State Management
    /// Start of memory - persistent memory
    pub const MEMORY: u32 = 32035;
    /// End of memory
    pub const MEMORY_END: u32 = 32036;
    /// Start of recall - memory retrieval
    pub const RECALL: u32 = 32037;
    /// End of recall
    pub const RECALL_END: u32 = 32038;

    // Control Tokens
    /// Padding token
    pub const PAD: u32 = 32039;
    /// Stop generation token
    pub const STOP: u32 = 32040;
    /// Separator token
    pub const SEP: u32 = 32041;

    // Multimodal Placeholders
    /// Start of image - image placeholder
    pub const IMAGE: u32 = 32042;
    /// End of image
    pub const IMAGE_END: u32 = 32043;
    /// Start of audio - audio placeholder
    pub const AUDIO: u32 = 32044;
    /// End of audio
    pub const AUDIO_END: u32 = 32045;
    /// Start of video - video placeholder
    pub const VIDEO: u32 = 32046;
    /// End of video
    pub const VIDEO_END: u32 = 32047;

    // Document Structure
    /// Start of title - document/section title
    pub const TITLE: u32 = 32048;
    /// End of title
    pub const TITLE_END: u32 = 32049;
    /// Start of section - semantic document section
    pub const SECTION: u32 = 32050;
    /// End of section
    pub const SECTION_END: u32 = 32051;
    /// Start of summary - condensed content summary
    pub const SUMMARY: u32 = 32052;
    /// End of summary
    pub const SUMMARY_END: u32 = 32053;
}

/// Agent tokens for Code Llama.
///
/// The 54-token block starts at 32016. Every id here is also reachable
/// at runtime as `from_pretrained("codellama")?.special_token_id(name)`;
/// these constants are the compile-time form, so a typo is a compile
/// error rather than a `None` to unwrap.
pub mod codellama_agent_tokens {
    // Conversation & Roles
    /// System role - system instructions
    pub const SYSTEM: u32 = 32016;
    /// User role - user input
    pub const USER: u32 = 32017;
    /// Assistant role - model output
    pub const ASSISTANT: u32 = 32018;
    /// Start of message - ChatML wrapper
    pub const IM_START: u32 = 32019;
    /// End of message - ChatML wrapper
    pub const IM_END: u32 = 32020;

    // Reasoning/Thinking
    /// Start of thinking - Chain-of-Thought
    pub const THINK: u32 = 32021;
    /// End of thinking
    pub const THINK_END: u32 = 32022;

    // ReAct Agent Loop
    /// Start of plan - action planning
    pub const PLAN: u32 = 32023;
    /// End of plan
    pub const PLAN_END: u32 = 32024;
    /// Start of step - individual action step
    pub const STEP: u32 = 32025;
    /// End of step
    pub const STEP_END: u32 = 32026;
    /// Start of action - agent action
    pub const ACT: u32 = 32027;
    /// End of action
    pub const ACT_END: u32 = 32028;
    /// Start of observation - environment feedback
    pub const OBSERVE: u32 = 32029;
    /// End of observation
    pub const OBSERVE_END: u32 = 32030;

    // Tool/Function Calling
    /// Start of function call - function invocation
    pub const FUNCTION: u32 = 32031;
    /// End of function call
    pub const FUNCTION_END: u32 = 32032;
    /// Start of function result - return value
    pub const RESULT: u32 = 32033;
    /// End of function result
    pub const RESULT_END: u32 = 32034;
    /// Start of error - error message
    pub const ERROR: u32 = 32035;
    /// End of error
    pub const ERROR_END: u32 = 32036;

    // Code Execution
    /// Start of code - inline code execution
    pub const CODE: u32 = 32037;
    /// End of code
    pub const CODE_END: u32 = 32038;
    /// Start of output - execution output
    pub const OUTPUT: u32 = 32039;
    /// End of output
    pub const OUTPUT_END: u32 = 32040;
    /// Start of language tag - code language
    pub const LANG: u32 = 32041;
    /// End of language tag
    pub const LANG_END: u32 = 32042;

    // RAG & Citations
    /// Start of context - retrieved context
    pub const CONTEXT: u32 = 32043;
    /// End of context
    pub const CONTEXT_END: u32 = 32044;
    /// Start of quote - exact citation
    pub const QUOTE: u32 = 32045;
    /// End of quote
    pub const QUOTE_END: u32 = 32046;
    /// Start of cite - citation reference
    pub const CITE: u32 = 32047;
    /// End of cite
    pub const CITE_END: u32 = 32048;
    /// Start of source - document source
    pub const SOURCE: u32 = 32049;
    /// End of source
    pub const SOURCE_END: u32 = 32050;

    // Memory/State Management
    /// Start of memory - persistent memory
    pub const MEMORY: u32 = 32051;
    /// End of memory
    pub const MEMORY_END: u32 = 32052;
    /// Start of recall - memory retrieval
    pub const RECALL: u32 = 32053;
    /// End of recall
    pub const RECALL_END: u32 = 32054;

    // Control Tokens
    /// Padding token
    pub const PAD: u32 = 32055;
    /// Stop generation token
    pub const STOP: u32 = 32056;
    /// Separator token
    pub const SEP: u32 = 32057;

    // Multimodal Placeholders
    /// Start of image - image placeholder
    pub const IMAGE: u32 = 32058;
    /// End of image
    pub const IMAGE_END: u32 = 32059;
    /// Start of audio - audio placeholder
    pub const AUDIO: u32 = 32060;
    /// End of audio
    pub const AUDIO_END: u32 = 32061;
    /// Start of video - video placeholder
    pub const VIDEO: u32 = 32062;
    /// End of video
    pub const VIDEO_END: u32 = 32063;

    // Document Structure
    /// Start of title - document/section title
    pub const TITLE: u32 = 32064;
    /// End of title
    pub const TITLE_END: u32 = 32065;
    /// Start of section - semantic document section
    pub const SECTION: u32 = 32066;
    /// End of section
    pub const SECTION_END: u32 = 32067;
    /// Start of summary - condensed content summary
    pub const SUMMARY: u32 = 32068;
    /// End of summary
    pub const SUMMARY_END: u32 = 32069;
}

/// Agent tokens for Answer.AI ModernBERT.
///
/// The 54-token block starts at 50368. Every id here is also reachable
/// at runtime as `from_pretrained("modernbert")?.special_token_id(name)`;
/// these constants are the compile-time form, so a typo is a compile
/// error rather than a `None` to unwrap.
pub mod modernbert_agent_tokens {
    // Conversation & Roles
    /// System role - system instructions
    pub const SYSTEM: u32 = 50368;
    /// User role - user input
    pub const USER: u32 = 50369;
    /// Assistant role - model output
    pub const ASSISTANT: u32 = 50370;
    /// Start of message - ChatML wrapper
    pub const IM_START: u32 = 50371;
    /// End of message - ChatML wrapper
    pub const IM_END: u32 = 50372;

    // Reasoning/Thinking
    /// Start of thinking - Chain-of-Thought
    pub const THINK: u32 = 50373;
    /// End of thinking
    pub const THINK_END: u32 = 50374;

    // ReAct Agent Loop
    /// Start of plan - action planning
    pub const PLAN: u32 = 50375;
    /// End of plan
    pub const PLAN_END: u32 = 50376;
    /// Start of step - individual action step
    pub const STEP: u32 = 50377;
    /// End of step
    pub const STEP_END: u32 = 50378;
    /// Start of action - agent action
    pub const ACT: u32 = 50379;
    /// End of action
    pub const ACT_END: u32 = 50380;
    /// Start of observation - environment feedback
    pub const OBSERVE: u32 = 50381;
    /// End of observation
    pub const OBSERVE_END: u32 = 50382;

    // Tool/Function Calling
    /// Start of function call - function invocation
    pub const FUNCTION: u32 = 50383;
    /// End of function call
    pub const FUNCTION_END: u32 = 50384;
    /// Start of function result - return value
    pub const RESULT: u32 = 50385;
    /// End of function result
    pub const RESULT_END: u32 = 50386;
    /// Start of error - error message
    pub const ERROR: u32 = 50387;
    /// End of error
    pub const ERROR_END: u32 = 50388;

    // Code Execution
    /// Start of code - inline code execution
    pub const CODE: u32 = 50389;
    /// End of code
    pub const CODE_END: u32 = 50390;
    /// Start of output - execution output
    pub const OUTPUT: u32 = 50391;
    /// End of output
    pub const OUTPUT_END: u32 = 50392;
    /// Start of language tag - code language
    pub const LANG: u32 = 50393;
    /// End of language tag
    pub const LANG_END: u32 = 50394;

    // RAG & Citations
    /// Start of context - retrieved context
    pub const CONTEXT: u32 = 50395;
    /// End of context
    pub const CONTEXT_END: u32 = 50396;
    /// Start of quote - exact citation
    pub const QUOTE: u32 = 50397;
    /// End of quote
    pub const QUOTE_END: u32 = 50398;
    /// Start of cite - citation reference
    pub const CITE: u32 = 50399;
    /// End of cite
    pub const CITE_END: u32 = 50400;
    /// Start of source - document source
    pub const SOURCE: u32 = 50401;
    /// End of source
    pub const SOURCE_END: u32 = 50402;

    // Memory/State Management
    /// Start of memory - persistent memory
    pub const MEMORY: u32 = 50403;
    /// End of memory
    pub const MEMORY_END: u32 = 50404;
    /// Start of recall - memory retrieval
    pub const RECALL: u32 = 50405;
    /// End of recall
    pub const RECALL_END: u32 = 50406;

    // Control Tokens
    /// Padding token
    pub const PAD: u32 = 50407;
    /// Stop generation token
    pub const STOP: u32 = 50408;
    /// Separator token
    pub const SEP: u32 = 50409;

    // Multimodal Placeholders
    /// Start of image - image placeholder
    pub const IMAGE: u32 = 50410;
    /// End of image
    pub const IMAGE_END: u32 = 50411;
    /// Start of audio - audio placeholder
    pub const AUDIO: u32 = 50412;
    /// End of audio
    pub const AUDIO_END: u32 = 50413;
    /// Start of video - video placeholder
    pub const VIDEO: u32 = 50414;
    /// End of video
    pub const VIDEO_END: u32 = 50415;

    // Document Structure
    /// Start of title - document/section title
    pub const TITLE: u32 = 50416;
    /// End of title
    pub const TITLE_END: u32 = 50417;
    /// Start of section - semantic document section
    pub const SECTION: u32 = 50418;
    /// End of section
    pub const SECTION_END: u32 = 50419;
    /// Start of summary - condensed content summary
    pub const SUMMARY: u32 = 50420;
    /// End of summary
    pub const SUMMARY_END: u32 = 50421;
}

