"""The `*_AGENT_TOKENS` classes must agree with the tokenizers they name.

Those classes are generated by `scripts/generate_agent_tokens.py` from a table
of `(constant, token, offset)` triples, entirely independently of
`insert_agent_tokens` in `src/core/pretrained.rs`. Two hand-maintained tables
for the same ids is exactly the shape that drifts: adding a bundled vocabulary
without regenerating leaves the class missing, and changing a base id leaves
every constant in it silently wrong — wrong in the worst way, since a constant
is what callers reach for precisely so they do not have to think about the id.

So this asserts the generated constants against `special_token_id` on the loaded
tokenizer, which is the same map `from_pretrained` builds. A constant that does
not match is a generator that was not re-run.
"""

import pytest

import splintr
from splintr import Tokenizer

# (constant name, token string) for the 54 agent tokens, in offset order. Kept
# here rather than imported from the generator so the test is an independent
# statement of the contract and not a restatement of the thing under test.
AGENT_TOKENS = [
    ("SYSTEM", "<|system|>"),
    ("USER", "<|user|>"),
    ("ASSISTANT", "<|assistant|>"),
    ("IM_START", "<|im_start|>"),
    ("IM_END", "<|im_end|>"),
    ("THINK", "<|think|>"),
    ("THINK_END", "<|/think|>"),
    ("PLAN", "<|plan|>"),
    ("PLAN_END", "<|/plan|>"),
    ("STEP", "<|step|>"),
    ("STEP_END", "<|/step|>"),
    ("ACT", "<|act|>"),
    ("ACT_END", "<|/act|>"),
    ("OBSERVE", "<|observe|>"),
    ("OBSERVE_END", "<|/observe|>"),
    ("FUNCTION", "<|function|>"),
    ("FUNCTION_END", "<|/function|>"),
    ("RESULT", "<|result|>"),
    ("RESULT_END", "<|/result|>"),
    ("ERROR", "<|error|>"),
    ("ERROR_END", "<|/error|>"),
    ("CODE", "<|code|>"),
    ("CODE_END", "<|/code|>"),
    ("OUTPUT", "<|output|>"),
    ("OUTPUT_END", "<|/output|>"),
    ("LANG", "<|lang|>"),
    ("LANG_END", "<|/lang|>"),
    ("CONTEXT", "<|context|>"),
    ("CONTEXT_END", "<|/context|>"),
    ("QUOTE", "<|quote|>"),
    ("QUOTE_END", "<|/quote|>"),
    ("CITE", "<|cite|>"),
    ("CITE_END", "<|/cite|>"),
    ("SOURCE", "<|source|>"),
    ("SOURCE_END", "<|/source|>"),
    ("MEMORY", "<|memory|>"),
    ("MEMORY_END", "<|/memory|>"),
    ("RECALL", "<|recall|>"),
    ("RECALL_END", "<|/recall|>"),
    ("PAD", "<|pad|>"),
    ("STOP", "<|stop|>"),
    ("SEP", "<|sep|>"),
    ("IMAGE", "<|image|>"),
    ("IMAGE_END", "<|/image|>"),
    ("AUDIO", "<|audio|>"),
    ("AUDIO_END", "<|/audio|>"),
    ("VIDEO", "<|video|>"),
    ("VIDEO_END", "<|/video|>"),
    ("TITLE", "<|title|>"),
    ("TITLE_END", "<|/title|>"),
    ("SECTION", "<|section|>"),
    ("SECTION_END", "<|/section|>"),
    ("SUMMARY", "<|summary|>"),
    ("SUMMARY_END", "<|/summary|>"),
]

# Every bundled vocabulary that carries agent tokens, paired with its constants
# class. Whisper is absent because it carries none — it is a speech model whose
# reserved ids are the standard Whisper set.
VOCABULARIES = [
    ("cl100k_base", "CL100K_AGENT_TOKENS"),
    ("o200k_base", "O200K_AGENT_TOKENS"),
    ("gpt-oss", "GPT_OSS_AGENT_TOKENS"),
    ("llama3", "LLAMA3_AGENT_TOKENS"),
    ("qwen3", "QWEN3_AGENT_TOKENS"),
    ("glm4", "GLM4_AGENT_TOKENS"),
    ("deepseek_v3", "DEEPSEEK_V3_AGENT_TOKENS"),
    ("mistral_v1", "MISTRAL_V1_AGENT_TOKENS"),
    ("mistral_v2", "MISTRAL_V2_AGENT_TOKENS"),
    ("mistral_v3", "MISTRAL_V3_AGENT_TOKENS"),
    ("kimi_k2", "KIMI_K2_AGENT_TOKENS"),
    ("kimi_k3", "KIMI_K3_AGENT_TOKENS"),
]


@pytest.mark.parametrize("vocab,class_name", VOCABULARIES)
def test_constants_match_the_tokenizer(vocab, class_name):
    """Every constant equals what the tokenizer resolves that token to."""
    constants = getattr(splintr, class_name)
    tokenizer = Tokenizer.from_pretrained(vocab)

    for const_name, token in AGENT_TOKENS:
        assert hasattr(constants, const_name), (
            f"{class_name}.{const_name} is missing — regenerate with "
            f"scripts/generate_agent_tokens.py"
        )
        assert getattr(constants, const_name) == tokenizer.special_token_id(token), (
            f"{class_name}.{const_name} disagrees with {vocab}'s own id for "
            f"{token!r} — regenerate with scripts/generate_agent_tokens.py"
        )


@pytest.mark.parametrize("vocab,class_name", VOCABULARIES)
def test_every_bundled_vocabulary_has_a_constants_class(vocab, class_name):
    """A bundled vocabulary added without regenerating fails here, not silently."""
    assert hasattr(splintr, class_name), f"splintr exports no {class_name}"
    assert class_name in splintr.__all__, f"{class_name} is not in splintr.__all__"


def test_vocabularies_that_ship_their_own_agent_names_keep_the_model_id():
    """Qwen and GLM define some agent-token names themselves.

    Those constants must carry the *model's* id, below `base_vocab_size` — the id
    the checkpoint was trained on — not a splintr-appended one. A chat template
    built from the constants would otherwise encode to ids the model never saw.
    """
    qwen_base = splintr.base_vocab_size("qwen3")
    assert splintr.QWEN3_AGENT_TOKENS.IM_START == 151644 < qwen_base
    assert splintr.QWEN3_AGENT_TOKENS.IM_END == 151645 < qwen_base
    # A name Qwen does not define still comes from the appended block.
    assert splintr.QWEN3_AGENT_TOKENS.SYSTEM == qwen_base

    glm_base = splintr.base_vocab_size("glm4")
    for const, expected in [
        ("SYSTEM", 151335),
        ("USER", 151336),
        ("ASSISTANT", 151337),
        ("IMAGE", 151363),
        ("VIDEO", 151364),
    ]:
        assert getattr(splintr.GLM4_AGENT_TOKENS, const) == expected < glm_base
    # GLM names only the opening markers, so the closing ones stay in the block.
    assert splintr.GLM4_AGENT_TOKENS.IMAGE_END == glm_base + 43
    assert splintr.GLM4_AGENT_TOKENS.VIDEO_END == glm_base + 47

    # Kimi: K2 names `<|im_end|>` (163586) and K3 names `<|sep|>` (163589), each
    # inside its 256-slot reserved block, well below the agent block at 163840.
    kimi_base = splintr.base_vocab_size("kimi_k2")
    assert splintr.KIMI_K2_AGENT_TOKENS.IM_END == 163586 < kimi_base
    assert splintr.KIMI_K3_AGENT_TOKENS.SEP == 163589 < kimi_base
    # The name each does NOT define still comes from the appended block.
    assert splintr.KIMI_K3_AGENT_TOKENS.IM_END == kimi_base + 4
    assert splintr.KIMI_K2_AGENT_TOKENS.SEP == kimi_base + 41


def test_constants_are_reachable_in_encoded_output():
    """The end the constants exist for: identifying a marker in real output."""
    tokenizer = Tokenizer.from_pretrained("qwen3")
    ids = tokenizer.encode_with_special("<|im_start|>system\nhi<|im_end|>")
    assert splintr.QWEN3_AGENT_TOKENS.IM_START in ids
    assert splintr.QWEN3_AGENT_TOKENS.IM_END in ids


@pytest.mark.parametrize("vocab,class_name", VOCABULARIES)
def test_special_tokens_enumerates_what_the_constants_name(vocab, class_name):
    """`special_tokens()` is the runtime answer the constants are the static one.

    The two must agree, or "list this vocabulary's markers" and "reach for the
    constant" give different pictures of the same tokenizer.
    """
    constants = getattr(splintr, class_name)
    listed = Tokenizer.from_pretrained(vocab).special_tokens()

    assert isinstance(listed, dict) and listed, f"{vocab} listed no special tokens"
    for const_name, token in AGENT_TOKENS:
        assert token in listed, f"{vocab} does not list {token!r}"
        assert listed[token] == getattr(constants, const_name)


def test_special_tokens_works_for_a_tokenizer_with_no_constants_class():
    """Whisper has no agent tokens and no class, but still enumerates."""
    listed = Tokenizer.from_pretrained("whisper").special_tokens()
    assert "<|startoftranscript|>" in listed
    assert "<|think|>" not in listed, "Whisper carries no agent tokens"
